// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/api.proto

package com.github.iotexproject.grpc.api;

public interface EstimateGasForActionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexapi.EstimateGasForActionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 gas = 1;</code>
   * @return The gas.
   */
  long getGas();
}
