// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/api.proto

package com.github.iotexproject.grpc.api;

public interface GetChainMetaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexapi.GetChainMetaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.iotextypes.ChainMeta chainMeta = 1;</code>
   * @return Whether the chainMeta field is set.
   */
  boolean hasChainMeta();
  /**
   * <code>.iotextypes.ChainMeta chainMeta = 1;</code>
   * @return The chainMeta.
   */
  com.github.iotexproject.grpc.types.ChainMeta getChainMeta();
  /**
   * <code>.iotextypes.ChainMeta chainMeta = 1;</code>
   */
  com.github.iotexproject.grpc.types.ChainMetaOrBuilder getChainMetaOrBuilder();

  /**
   * <pre>
   * sync stage
   * </pre>
   *
   * <code>string syncStage = 2;</code>
   * @return The syncStage.
   */
  java.lang.String getSyncStage();
  /**
   * <pre>
   * sync stage
   * </pre>
   *
   * <code>string syncStage = 2;</code>
   * @return The bytes for syncStage.
   */
  com.google.protobuf.ByteString
      getSyncStageBytes();
}
