// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/api.proto

package com.github.iotexproject.grpc.api;

public interface GetChainMetaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexapi.GetChainMetaRequest)
    com.google.protobuf.MessageOrBuilder {
}
