// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/api.proto

package com.github.iotexproject.grpc.api;

public interface GetEvmTransfersByActionHashResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexapi.GetEvmTransfersByActionHashResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.iotextypes.ActionEvmTransfer actionEvmTransfers = 1;</code>
   * @return Whether the actionEvmTransfers field is set.
   */
  boolean hasActionEvmTransfers();
  /**
   * <code>.iotextypes.ActionEvmTransfer actionEvmTransfers = 1;</code>
   * @return The actionEvmTransfers.
   */
  com.github.iotexproject.grpc.types.ActionEvmTransfer getActionEvmTransfers();
  /**
   * <code>.iotextypes.ActionEvmTransfer actionEvmTransfers = 1;</code>
   */
  com.github.iotexproject.grpc.types.ActionEvmTransferOrBuilder getActionEvmTransfersOrBuilder();
}
