// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/api.proto

package com.github.iotexproject.grpc.api;

public interface GetTransactionLogByBlockHeightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexapi.GetTransactionLogByBlockHeightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
   * @return Whether the transactionLogs field is set.
   */
  boolean hasTransactionLogs();
  /**
   * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
   * @return The transactionLogs.
   */
  com.github.iotexproject.grpc.types.TransactionLogs getTransactionLogs();
  /**
   * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
   */
  com.github.iotexproject.grpc.types.TransactionLogsOrBuilder getTransactionLogsOrBuilder();

  /**
   * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
   * @return Whether the blockIdentifier field is set.
   */
  boolean hasBlockIdentifier();
  /**
   * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
   * @return The blockIdentifier.
   */
  com.github.iotexproject.grpc.types.BlockIdentifier getBlockIdentifier();
  /**
   * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
   */
  com.github.iotexproject.grpc.types.BlockIdentifierOrBuilder getBlockIdentifierOrBuilder();
}
