// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/api.proto

package com.github.iotexproject.grpc.api;

/**
 * Protobuf type {@code iotexapi.GetTransactionLogByBlockHeightResponse}
 */
public final class GetTransactionLogByBlockHeightResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iotexapi.GetTransactionLogByBlockHeightResponse)
    GetTransactionLogByBlockHeightResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTransactionLogByBlockHeightResponse.newBuilder() to construct.
  private GetTransactionLogByBlockHeightResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTransactionLogByBlockHeightResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTransactionLogByBlockHeightResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTransactionLogByBlockHeightResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.github.iotexproject.grpc.types.TransactionLogs.Builder subBuilder = null;
            if (transactionLogs_ != null) {
              subBuilder = transactionLogs_.toBuilder();
            }
            transactionLogs_ = input.readMessage(com.github.iotexproject.grpc.types.TransactionLogs.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(transactionLogs_);
              transactionLogs_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.github.iotexproject.grpc.types.BlockIdentifier.Builder subBuilder = null;
            if (blockIdentifier_ != null) {
              subBuilder = blockIdentifier_.toBuilder();
            }
            blockIdentifier_ = input.readMessage(com.github.iotexproject.grpc.types.BlockIdentifier.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(blockIdentifier_);
              blockIdentifier_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetTransactionLogByBlockHeightResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetTransactionLogByBlockHeightResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse.class, com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse.Builder.class);
  }

  public static final int TRANSACTIONLOGS_FIELD_NUMBER = 1;
  private com.github.iotexproject.grpc.types.TransactionLogs transactionLogs_;
  /**
   * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
   * @return Whether the transactionLogs field is set.
   */
  @java.lang.Override
  public boolean hasTransactionLogs() {
    return transactionLogs_ != null;
  }
  /**
   * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
   * @return The transactionLogs.
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.TransactionLogs getTransactionLogs() {
    return transactionLogs_ == null ? com.github.iotexproject.grpc.types.TransactionLogs.getDefaultInstance() : transactionLogs_;
  }
  /**
   * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.TransactionLogsOrBuilder getTransactionLogsOrBuilder() {
    return getTransactionLogs();
  }

  public static final int BLOCKIDENTIFIER_FIELD_NUMBER = 2;
  private com.github.iotexproject.grpc.types.BlockIdentifier blockIdentifier_;
  /**
   * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
   * @return Whether the blockIdentifier field is set.
   */
  @java.lang.Override
  public boolean hasBlockIdentifier() {
    return blockIdentifier_ != null;
  }
  /**
   * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
   * @return The blockIdentifier.
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.BlockIdentifier getBlockIdentifier() {
    return blockIdentifier_ == null ? com.github.iotexproject.grpc.types.BlockIdentifier.getDefaultInstance() : blockIdentifier_;
  }
  /**
   * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.BlockIdentifierOrBuilder getBlockIdentifierOrBuilder() {
    return getBlockIdentifier();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (transactionLogs_ != null) {
      output.writeMessage(1, getTransactionLogs());
    }
    if (blockIdentifier_ != null) {
      output.writeMessage(2, getBlockIdentifier());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (transactionLogs_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTransactionLogs());
    }
    if (blockIdentifier_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBlockIdentifier());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse other = (com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse) obj;

    if (hasTransactionLogs() != other.hasTransactionLogs()) return false;
    if (hasTransactionLogs()) {
      if (!getTransactionLogs()
          .equals(other.getTransactionLogs())) return false;
    }
    if (hasBlockIdentifier() != other.hasBlockIdentifier()) return false;
    if (hasBlockIdentifier()) {
      if (!getBlockIdentifier()
          .equals(other.getBlockIdentifier())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTransactionLogs()) {
      hash = (37 * hash) + TRANSACTIONLOGS_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionLogs().hashCode();
    }
    if (hasBlockIdentifier()) {
      hash = (37 * hash) + BLOCKIDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getBlockIdentifier().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotexapi.GetTransactionLogByBlockHeightResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotexapi.GetTransactionLogByBlockHeightResponse)
      com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetTransactionLogByBlockHeightResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetTransactionLogByBlockHeightResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse.class, com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (transactionLogsBuilder_ == null) {
        transactionLogs_ = null;
      } else {
        transactionLogs_ = null;
        transactionLogsBuilder_ = null;
      }
      if (blockIdentifierBuilder_ == null) {
        blockIdentifier_ = null;
      } else {
        blockIdentifier_ = null;
        blockIdentifierBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetTransactionLogByBlockHeightResponse_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse build() {
      com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse buildPartial() {
      com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse result = new com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse(this);
      if (transactionLogsBuilder_ == null) {
        result.transactionLogs_ = transactionLogs_;
      } else {
        result.transactionLogs_ = transactionLogsBuilder_.build();
      }
      if (blockIdentifierBuilder_ == null) {
        result.blockIdentifier_ = blockIdentifier_;
      } else {
        result.blockIdentifier_ = blockIdentifierBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse) {
        return mergeFrom((com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse other) {
      if (other == com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse.getDefaultInstance()) return this;
      if (other.hasTransactionLogs()) {
        mergeTransactionLogs(other.getTransactionLogs());
      }
      if (other.hasBlockIdentifier()) {
        mergeBlockIdentifier(other.getBlockIdentifier());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.github.iotexproject.grpc.types.TransactionLogs transactionLogs_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.iotexproject.grpc.types.TransactionLogs, com.github.iotexproject.grpc.types.TransactionLogs.Builder, com.github.iotexproject.grpc.types.TransactionLogsOrBuilder> transactionLogsBuilder_;
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     * @return Whether the transactionLogs field is set.
     */
    public boolean hasTransactionLogs() {
      return transactionLogsBuilder_ != null || transactionLogs_ != null;
    }
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     * @return The transactionLogs.
     */
    public com.github.iotexproject.grpc.types.TransactionLogs getTransactionLogs() {
      if (transactionLogsBuilder_ == null) {
        return transactionLogs_ == null ? com.github.iotexproject.grpc.types.TransactionLogs.getDefaultInstance() : transactionLogs_;
      } else {
        return transactionLogsBuilder_.getMessage();
      }
    }
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     */
    public Builder setTransactionLogs(com.github.iotexproject.grpc.types.TransactionLogs value) {
      if (transactionLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transactionLogs_ = value;
        onChanged();
      } else {
        transactionLogsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     */
    public Builder setTransactionLogs(
        com.github.iotexproject.grpc.types.TransactionLogs.Builder builderForValue) {
      if (transactionLogsBuilder_ == null) {
        transactionLogs_ = builderForValue.build();
        onChanged();
      } else {
        transactionLogsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     */
    public Builder mergeTransactionLogs(com.github.iotexproject.grpc.types.TransactionLogs value) {
      if (transactionLogsBuilder_ == null) {
        if (transactionLogs_ != null) {
          transactionLogs_ =
            com.github.iotexproject.grpc.types.TransactionLogs.newBuilder(transactionLogs_).mergeFrom(value).buildPartial();
        } else {
          transactionLogs_ = value;
        }
        onChanged();
      } else {
        transactionLogsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     */
    public Builder clearTransactionLogs() {
      if (transactionLogsBuilder_ == null) {
        transactionLogs_ = null;
        onChanged();
      } else {
        transactionLogs_ = null;
        transactionLogsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     */
    public com.github.iotexproject.grpc.types.TransactionLogs.Builder getTransactionLogsBuilder() {
      
      onChanged();
      return getTransactionLogsFieldBuilder().getBuilder();
    }
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     */
    public com.github.iotexproject.grpc.types.TransactionLogsOrBuilder getTransactionLogsOrBuilder() {
      if (transactionLogsBuilder_ != null) {
        return transactionLogsBuilder_.getMessageOrBuilder();
      } else {
        return transactionLogs_ == null ?
            com.github.iotexproject.grpc.types.TransactionLogs.getDefaultInstance() : transactionLogs_;
      }
    }
    /**
     * <code>.iotextypes.TransactionLogs transactionLogs = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.iotexproject.grpc.types.TransactionLogs, com.github.iotexproject.grpc.types.TransactionLogs.Builder, com.github.iotexproject.grpc.types.TransactionLogsOrBuilder> 
        getTransactionLogsFieldBuilder() {
      if (transactionLogsBuilder_ == null) {
        transactionLogsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.iotexproject.grpc.types.TransactionLogs, com.github.iotexproject.grpc.types.TransactionLogs.Builder, com.github.iotexproject.grpc.types.TransactionLogsOrBuilder>(
                getTransactionLogs(),
                getParentForChildren(),
                isClean());
        transactionLogs_ = null;
      }
      return transactionLogsBuilder_;
    }

    private com.github.iotexproject.grpc.types.BlockIdentifier blockIdentifier_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.iotexproject.grpc.types.BlockIdentifier, com.github.iotexproject.grpc.types.BlockIdentifier.Builder, com.github.iotexproject.grpc.types.BlockIdentifierOrBuilder> blockIdentifierBuilder_;
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     * @return Whether the blockIdentifier field is set.
     */
    public boolean hasBlockIdentifier() {
      return blockIdentifierBuilder_ != null || blockIdentifier_ != null;
    }
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     * @return The blockIdentifier.
     */
    public com.github.iotexproject.grpc.types.BlockIdentifier getBlockIdentifier() {
      if (blockIdentifierBuilder_ == null) {
        return blockIdentifier_ == null ? com.github.iotexproject.grpc.types.BlockIdentifier.getDefaultInstance() : blockIdentifier_;
      } else {
        return blockIdentifierBuilder_.getMessage();
      }
    }
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     */
    public Builder setBlockIdentifier(com.github.iotexproject.grpc.types.BlockIdentifier value) {
      if (blockIdentifierBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        blockIdentifier_ = value;
        onChanged();
      } else {
        blockIdentifierBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     */
    public Builder setBlockIdentifier(
        com.github.iotexproject.grpc.types.BlockIdentifier.Builder builderForValue) {
      if (blockIdentifierBuilder_ == null) {
        blockIdentifier_ = builderForValue.build();
        onChanged();
      } else {
        blockIdentifierBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     */
    public Builder mergeBlockIdentifier(com.github.iotexproject.grpc.types.BlockIdentifier value) {
      if (blockIdentifierBuilder_ == null) {
        if (blockIdentifier_ != null) {
          blockIdentifier_ =
            com.github.iotexproject.grpc.types.BlockIdentifier.newBuilder(blockIdentifier_).mergeFrom(value).buildPartial();
        } else {
          blockIdentifier_ = value;
        }
        onChanged();
      } else {
        blockIdentifierBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     */
    public Builder clearBlockIdentifier() {
      if (blockIdentifierBuilder_ == null) {
        blockIdentifier_ = null;
        onChanged();
      } else {
        blockIdentifier_ = null;
        blockIdentifierBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     */
    public com.github.iotexproject.grpc.types.BlockIdentifier.Builder getBlockIdentifierBuilder() {
      
      onChanged();
      return getBlockIdentifierFieldBuilder().getBuilder();
    }
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     */
    public com.github.iotexproject.grpc.types.BlockIdentifierOrBuilder getBlockIdentifierOrBuilder() {
      if (blockIdentifierBuilder_ != null) {
        return blockIdentifierBuilder_.getMessageOrBuilder();
      } else {
        return blockIdentifier_ == null ?
            com.github.iotexproject.grpc.types.BlockIdentifier.getDefaultInstance() : blockIdentifier_;
      }
    }
    /**
     * <code>.iotextypes.BlockIdentifier blockIdentifier = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.iotexproject.grpc.types.BlockIdentifier, com.github.iotexproject.grpc.types.BlockIdentifier.Builder, com.github.iotexproject.grpc.types.BlockIdentifierOrBuilder> 
        getBlockIdentifierFieldBuilder() {
      if (blockIdentifierBuilder_ == null) {
        blockIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.iotexproject.grpc.types.BlockIdentifier, com.github.iotexproject.grpc.types.BlockIdentifier.Builder, com.github.iotexproject.grpc.types.BlockIdentifierOrBuilder>(
                getBlockIdentifier(),
                getParentForChildren(),
                isClean());
        blockIdentifier_ = null;
      }
      return blockIdentifierBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iotexapi.GetTransactionLogByBlockHeightResponse)
  }

  // @@protoc_insertion_point(class_scope:iotexapi.GetTransactionLogByBlockHeightResponse)
  private static final com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse();
  }

  public static com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTransactionLogByBlockHeightResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetTransactionLogByBlockHeightResponse>() {
    @java.lang.Override
    public GetTransactionLogByBlockHeightResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTransactionLogByBlockHeightResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTransactionLogByBlockHeightResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTransactionLogByBlockHeightResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.api.GetTransactionLogByBlockHeightResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

