// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/api.proto

package com.github.iotexproject.grpc.api;

/**
 * Protobuf type {@code iotexapi.ReadStateRequest}
 */
public final class ReadStateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iotexapi.ReadStateRequest)
    ReadStateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReadStateRequest.newBuilder() to construct.
  private ReadStateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReadStateRequest() {
    protocolID_ = com.google.protobuf.ByteString.EMPTY;
    methodName_ = com.google.protobuf.ByteString.EMPTY;
    arguments_ = java.util.Collections.emptyList();
    height_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReadStateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReadStateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            protocolID_ = input.readBytes();
            break;
          }
          case 18: {

            methodName_ = input.readBytes();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              arguments_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            arguments_.add(input.readBytes());
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            height_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        arguments_ = java.util.Collections.unmodifiableList(arguments_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_ReadStateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_ReadStateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.api.ReadStateRequest.class, com.github.iotexproject.grpc.api.ReadStateRequest.Builder.class);
  }

  public static final int PROTOCOLID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString protocolID_;
  /**
   * <code>bytes protocolID = 1;</code>
   * @return The protocolID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProtocolID() {
    return protocolID_;
  }

  public static final int METHODNAME_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString methodName_;
  /**
   * <code>bytes methodName = 2;</code>
   * @return The methodName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMethodName() {
    return methodName_;
  }

  public static final int ARGUMENTS_FIELD_NUMBER = 3;
  private java.util.List<com.google.protobuf.ByteString> arguments_;
  /**
   * <code>repeated bytes arguments = 3;</code>
   * @return A list containing the arguments.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getArgumentsList() {
    return arguments_;
  }
  /**
   * <code>repeated bytes arguments = 3;</code>
   * @return The count of arguments.
   */
  public int getArgumentsCount() {
    return arguments_.size();
  }
  /**
   * <code>repeated bytes arguments = 3;</code>
   * @param index The index of the element to return.
   * @return The arguments at the given index.
   */
  public com.google.protobuf.ByteString getArguments(int index) {
    return arguments_.get(index);
  }

  public static final int HEIGHT_FIELD_NUMBER = 4;
  private volatile java.lang.Object height_;
  /**
   * <pre>
   * optional, if not present, read from tip height
   * </pre>
   *
   * <code>string height = 4;</code>
   * @return The height.
   */
  @java.lang.Override
  public java.lang.String getHeight() {
    java.lang.Object ref = height_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      height_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional, if not present, read from tip height
   * </pre>
   *
   * <code>string height = 4;</code>
   * @return The bytes for height.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHeightBytes() {
    java.lang.Object ref = height_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      height_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!protocolID_.isEmpty()) {
      output.writeBytes(1, protocolID_);
    }
    if (!methodName_.isEmpty()) {
      output.writeBytes(2, methodName_);
    }
    for (int i = 0; i < arguments_.size(); i++) {
      output.writeBytes(3, arguments_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(height_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, height_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!protocolID_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, protocolID_);
    }
    if (!methodName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, methodName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < arguments_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(arguments_.get(i));
      }
      size += dataSize;
      size += 1 * getArgumentsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(height_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, height_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.api.ReadStateRequest)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.api.ReadStateRequest other = (com.github.iotexproject.grpc.api.ReadStateRequest) obj;

    if (!getProtocolID()
        .equals(other.getProtocolID())) return false;
    if (!getMethodName()
        .equals(other.getMethodName())) return false;
    if (!getArgumentsList()
        .equals(other.getArgumentsList())) return false;
    if (!getHeight()
        .equals(other.getHeight())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROTOCOLID_FIELD_NUMBER;
    hash = (53 * hash) + getProtocolID().hashCode();
    hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
    hash = (53 * hash) + getMethodName().hashCode();
    if (getArgumentsCount() > 0) {
      hash = (37 * hash) + ARGUMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getArgumentsList().hashCode();
    }
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getHeight().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.ReadStateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.api.ReadStateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotexapi.ReadStateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotexapi.ReadStateRequest)
      com.github.iotexproject.grpc.api.ReadStateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_ReadStateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_ReadStateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.api.ReadStateRequest.class, com.github.iotexproject.grpc.api.ReadStateRequest.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.api.ReadStateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      protocolID_ = com.google.protobuf.ByteString.EMPTY;

      methodName_ = com.google.protobuf.ByteString.EMPTY;

      arguments_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      height_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_ReadStateRequest_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.ReadStateRequest getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.api.ReadStateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.ReadStateRequest build() {
      com.github.iotexproject.grpc.api.ReadStateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.ReadStateRequest buildPartial() {
      com.github.iotexproject.grpc.api.ReadStateRequest result = new com.github.iotexproject.grpc.api.ReadStateRequest(this);
      int from_bitField0_ = bitField0_;
      result.protocolID_ = protocolID_;
      result.methodName_ = methodName_;
      if (((bitField0_ & 0x00000001) != 0)) {
        arguments_ = java.util.Collections.unmodifiableList(arguments_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.arguments_ = arguments_;
      result.height_ = height_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.api.ReadStateRequest) {
        return mergeFrom((com.github.iotexproject.grpc.api.ReadStateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.api.ReadStateRequest other) {
      if (other == com.github.iotexproject.grpc.api.ReadStateRequest.getDefaultInstance()) return this;
      if (other.getProtocolID() != com.google.protobuf.ByteString.EMPTY) {
        setProtocolID(other.getProtocolID());
      }
      if (other.getMethodName() != com.google.protobuf.ByteString.EMPTY) {
        setMethodName(other.getMethodName());
      }
      if (!other.arguments_.isEmpty()) {
        if (arguments_.isEmpty()) {
          arguments_ = other.arguments_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureArgumentsIsMutable();
          arguments_.addAll(other.arguments_);
        }
        onChanged();
      }
      if (!other.getHeight().isEmpty()) {
        height_ = other.height_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.iotexproject.grpc.api.ReadStateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.iotexproject.grpc.api.ReadStateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString protocolID_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes protocolID = 1;</code>
     * @return The protocolID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProtocolID() {
      return protocolID_;
    }
    /**
     * <code>bytes protocolID = 1;</code>
     * @param value The protocolID to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolID(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protocolID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes protocolID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolID() {
      
      protocolID_ = getDefaultInstance().getProtocolID();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString methodName_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes methodName = 2;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMethodName() {
      return methodName_;
    }
    /**
     * <code>bytes methodName = 2;</code>
     * @param value The methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodName(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      methodName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes methodName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodName() {
      
      methodName_ = getDefaultInstance().getMethodName();
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> arguments_ = java.util.Collections.emptyList();
    private void ensureArgumentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        arguments_ = new java.util.ArrayList<com.google.protobuf.ByteString>(arguments_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated bytes arguments = 3;</code>
     * @return A list containing the arguments.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getArgumentsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(arguments_) : arguments_;
    }
    /**
     * <code>repeated bytes arguments = 3;</code>
     * @return The count of arguments.
     */
    public int getArgumentsCount() {
      return arguments_.size();
    }
    /**
     * <code>repeated bytes arguments = 3;</code>
     * @param index The index of the element to return.
     * @return The arguments at the given index.
     */
    public com.google.protobuf.ByteString getArguments(int index) {
      return arguments_.get(index);
    }
    /**
     * <code>repeated bytes arguments = 3;</code>
     * @param index The index to set the value at.
     * @param value The arguments to set.
     * @return This builder for chaining.
     */
    public Builder setArguments(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentsIsMutable();
      arguments_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes arguments = 3;</code>
     * @param value The arguments to add.
     * @return This builder for chaining.
     */
    public Builder addArguments(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentsIsMutable();
      arguments_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes arguments = 3;</code>
     * @param values The arguments to add.
     * @return This builder for chaining.
     */
    public Builder addAllArguments(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureArgumentsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, arguments_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes arguments = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearArguments() {
      arguments_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.lang.Object height_ = "";
    /**
     * <pre>
     * optional, if not present, read from tip height
     * </pre>
     *
     * <code>string height = 4;</code>
     * @return The height.
     */
    public java.lang.String getHeight() {
      java.lang.Object ref = height_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        height_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional, if not present, read from tip height
     * </pre>
     *
     * <code>string height = 4;</code>
     * @return The bytes for height.
     */
    public com.google.protobuf.ByteString
        getHeightBytes() {
      java.lang.Object ref = height_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        height_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional, if not present, read from tip height
     * </pre>
     *
     * <code>string height = 4;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional, if not present, read from tip height
     * </pre>
     *
     * <code>string height = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      
      height_ = getDefaultInstance().getHeight();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional, if not present, read from tip height
     * </pre>
     *
     * <code>string height = 4;</code>
     * @param value The bytes for height to set.
     * @return This builder for chaining.
     */
    public Builder setHeightBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      height_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iotexapi.ReadStateRequest)
  }

  // @@protoc_insertion_point(class_scope:iotexapi.ReadStateRequest)
  private static final com.github.iotexproject.grpc.api.ReadStateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.api.ReadStateRequest();
  }

  public static com.github.iotexproject.grpc.api.ReadStateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReadStateRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReadStateRequest>() {
    @java.lang.Override
    public ReadStateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReadStateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReadStateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReadStateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.api.ReadStateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

