// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/api.proto

package com.github.iotexproject.grpc.api;

public interface StreamLogsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexapi.StreamLogsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.iotexapi.LogsFilter filter = 1;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>.iotexapi.LogsFilter filter = 1;</code>
   * @return The filter.
   */
  com.github.iotexproject.grpc.api.LogsFilter getFilter();
  /**
   * <code>.iotexapi.LogsFilter filter = 1;</code>
   */
  com.github.iotexproject.grpc.api.LogsFilterOrBuilder getFilterOrBuilder();
}
