// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/rpc/rpc.proto

package com.github.iotexproject.grpc.rpc;

/**
 * Protobuf type {@code iotexrpc.ActionSync}
 */
public final class ActionSync extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iotexrpc.ActionSync)
    ActionSyncOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActionSync.newBuilder() to construct.
  private ActionSync(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActionSync() {
    hashes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActionSync();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ActionSync(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              hashes_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            hashes_.add(input.readBytes());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        hashes_ = java.util.Collections.unmodifiableList(hashes_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.rpc.ActionSync.class, com.github.iotexproject.grpc.rpc.ActionSync.Builder.class);
  }

  public static final int HASHES_FIELD_NUMBER = 1;
  private java.util.List<com.google.protobuf.ByteString> hashes_;
  /**
   * <code>repeated bytes hashes = 1;</code>
   * @return A list containing the hashes.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getHashesList() {
    return hashes_;
  }
  /**
   * <code>repeated bytes hashes = 1;</code>
   * @return The count of hashes.
   */
  public int getHashesCount() {
    return hashes_.size();
  }
  /**
   * <code>repeated bytes hashes = 1;</code>
   * @param index The index of the element to return.
   * @return The hashes at the given index.
   */
  public com.google.protobuf.ByteString getHashes(int index) {
    return hashes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < hashes_.size(); i++) {
      output.writeBytes(1, hashes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < hashes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(hashes_.get(i));
      }
      size += dataSize;
      size += 1 * getHashesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.rpc.ActionSync)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.rpc.ActionSync other = (com.github.iotexproject.grpc.rpc.ActionSync) obj;

    if (!getHashesList()
        .equals(other.getHashesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHashesCount() > 0) {
      hash = (37 * hash) + HASHES_FIELD_NUMBER;
      hash = (53 * hash) + getHashesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.rpc.ActionSync prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotexrpc.ActionSync}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotexrpc.ActionSync)
      com.github.iotexproject.grpc.rpc.ActionSyncOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.rpc.ActionSync.class, com.github.iotexproject.grpc.rpc.ActionSync.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.rpc.ActionSync.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hashes_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.rpc.ActionSync getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.rpc.ActionSync.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.rpc.ActionSync build() {
      com.github.iotexproject.grpc.rpc.ActionSync result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.rpc.ActionSync buildPartial() {
      com.github.iotexproject.grpc.rpc.ActionSync result = new com.github.iotexproject.grpc.rpc.ActionSync(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        hashes_ = java.util.Collections.unmodifiableList(hashes_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.hashes_ = hashes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.rpc.ActionSync) {
        return mergeFrom((com.github.iotexproject.grpc.rpc.ActionSync)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.rpc.ActionSync other) {
      if (other == com.github.iotexproject.grpc.rpc.ActionSync.getDefaultInstance()) return this;
      if (!other.hashes_.isEmpty()) {
        if (hashes_.isEmpty()) {
          hashes_ = other.hashes_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureHashesIsMutable();
          hashes_.addAll(other.hashes_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.iotexproject.grpc.rpc.ActionSync parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.iotexproject.grpc.rpc.ActionSync) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.protobuf.ByteString> hashes_ = java.util.Collections.emptyList();
    private void ensureHashesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        hashes_ = new java.util.ArrayList<com.google.protobuf.ByteString>(hashes_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @return A list containing the hashes.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getHashesList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(hashes_) : hashes_;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @return The count of hashes.
     */
    public int getHashesCount() {
      return hashes_.size();
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @param index The index of the element to return.
     * @return The hashes at the given index.
     */
    public com.google.protobuf.ByteString getHashes(int index) {
      return hashes_.get(index);
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @param index The index to set the value at.
     * @param value The hashes to set.
     * @return This builder for chaining.
     */
    public Builder setHashes(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHashesIsMutable();
      hashes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @param value The hashes to add.
     * @return This builder for chaining.
     */
    public Builder addHashes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHashesIsMutable();
      hashes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @param values The hashes to add.
     * @return This builder for chaining.
     */
    public Builder addAllHashes(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureHashesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hashes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHashes() {
      hashes_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iotexrpc.ActionSync)
  }

  // @@protoc_insertion_point(class_scope:iotexrpc.ActionSync)
  private static final com.github.iotexproject.grpc.rpc.ActionSync DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.rpc.ActionSync();
  }

  public static com.github.iotexproject.grpc.rpc.ActionSync getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionSync>
      PARSER = new com.google.protobuf.AbstractParser<ActionSync>() {
    @java.lang.Override
    public ActionSync parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ActionSync(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActionSync> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionSync> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.rpc.ActionSync getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

