// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/testing/testing.proto

package com.github.iotexproject.grpc.testing;

public final class Testing {
  private Testing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testingpb_TestPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testingpb_TestPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033proto/testing/testing.proto\022\ttestingpb" +
      "\"\037\n\013TestPayload\022\020\n\010msg_body\030\001 \001(\014B^\n$com" +
      ".github.iotexproject.grpc.testingP\001Z4git" +
      "hub.com/iotexproject/iotex-proto/golang/" +
      "testingpbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_testingpb_TestPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_testingpb_TestPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testingpb_TestPayload_descriptor,
        new java.lang.String[] { "MsgBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
