// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/testing/testing.proto

package com.github.iotexproject.grpc.testing;

public interface TestPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testingpb.TestPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes msg_body = 1;</code>
   * @return The msgBody.
   */
  com.google.protobuf.ByteString getMsgBody();
}
