// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/action.proto

package com.github.iotexproject.grpc.types;

public interface CandidateActivateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotextypes.CandidateActivate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 bucketIndex = 1;</code>
   * @return The bucketIndex.
   */
  long getBucketIndex();
}
