// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/action.proto

package com.github.iotexproject.grpc.types;

/**
 * <pre>
 * Deprecated
 * </pre>
 *
 * Protobuf type {@code iotextypes.EvmTransferList}
 */
public final class EvmTransferList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iotextypes.EvmTransferList)
    EvmTransferListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EvmTransferList.newBuilder() to construct.
  private EvmTransferList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EvmTransferList() {
    evmTransfers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EvmTransferList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EvmTransferList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              evmTransfers_ = new java.util.ArrayList<com.github.iotexproject.grpc.types.EvmTransfer>();
              mutable_bitField0_ |= 0x00000001;
            }
            evmTransfers_.add(
                input.readMessage(com.github.iotexproject.grpc.types.EvmTransfer.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        evmTransfers_ = java.util.Collections.unmodifiableList(evmTransfers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_EvmTransferList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_EvmTransferList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.types.EvmTransferList.class, com.github.iotexproject.grpc.types.EvmTransferList.Builder.class);
  }

  public static final int EVMTRANSFERS_FIELD_NUMBER = 1;
  private java.util.List<com.github.iotexproject.grpc.types.EvmTransfer> evmTransfers_;
  /**
   * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.iotexproject.grpc.types.EvmTransfer> getEvmTransfersList() {
    return evmTransfers_;
  }
  /**
   * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.iotexproject.grpc.types.EvmTransferOrBuilder> 
      getEvmTransfersOrBuilderList() {
    return evmTransfers_;
  }
  /**
   * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
   */
  @java.lang.Override
  public int getEvmTransfersCount() {
    return evmTransfers_.size();
  }
  /**
   * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.EvmTransfer getEvmTransfers(int index) {
    return evmTransfers_.get(index);
  }
  /**
   * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.EvmTransferOrBuilder getEvmTransfersOrBuilder(
      int index) {
    return evmTransfers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < evmTransfers_.size(); i++) {
      output.writeMessage(1, evmTransfers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < evmTransfers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, evmTransfers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.types.EvmTransferList)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.types.EvmTransferList other = (com.github.iotexproject.grpc.types.EvmTransferList) obj;

    if (!getEvmTransfersList()
        .equals(other.getEvmTransfersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEvmTransfersCount() > 0) {
      hash = (37 * hash) + EVMTRANSFERS_FIELD_NUMBER;
      hash = (53 * hash) + getEvmTransfersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.EvmTransferList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.types.EvmTransferList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Deprecated
   * </pre>
   *
   * Protobuf type {@code iotextypes.EvmTransferList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotextypes.EvmTransferList)
      com.github.iotexproject.grpc.types.EvmTransferListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_EvmTransferList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_EvmTransferList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.types.EvmTransferList.class, com.github.iotexproject.grpc.types.EvmTransferList.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.types.EvmTransferList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEvmTransfersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (evmTransfersBuilder_ == null) {
        evmTransfers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        evmTransfersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_EvmTransferList_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.EvmTransferList getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.types.EvmTransferList.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.EvmTransferList build() {
      com.github.iotexproject.grpc.types.EvmTransferList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.EvmTransferList buildPartial() {
      com.github.iotexproject.grpc.types.EvmTransferList result = new com.github.iotexproject.grpc.types.EvmTransferList(this);
      int from_bitField0_ = bitField0_;
      if (evmTransfersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          evmTransfers_ = java.util.Collections.unmodifiableList(evmTransfers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.evmTransfers_ = evmTransfers_;
      } else {
        result.evmTransfers_ = evmTransfersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.types.EvmTransferList) {
        return mergeFrom((com.github.iotexproject.grpc.types.EvmTransferList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.types.EvmTransferList other) {
      if (other == com.github.iotexproject.grpc.types.EvmTransferList.getDefaultInstance()) return this;
      if (evmTransfersBuilder_ == null) {
        if (!other.evmTransfers_.isEmpty()) {
          if (evmTransfers_.isEmpty()) {
            evmTransfers_ = other.evmTransfers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEvmTransfersIsMutable();
            evmTransfers_.addAll(other.evmTransfers_);
          }
          onChanged();
        }
      } else {
        if (!other.evmTransfers_.isEmpty()) {
          if (evmTransfersBuilder_.isEmpty()) {
            evmTransfersBuilder_.dispose();
            evmTransfersBuilder_ = null;
            evmTransfers_ = other.evmTransfers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            evmTransfersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEvmTransfersFieldBuilder() : null;
          } else {
            evmTransfersBuilder_.addAllMessages(other.evmTransfers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.iotexproject.grpc.types.EvmTransferList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.iotexproject.grpc.types.EvmTransferList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.github.iotexproject.grpc.types.EvmTransfer> evmTransfers_ =
      java.util.Collections.emptyList();
    private void ensureEvmTransfersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        evmTransfers_ = new java.util.ArrayList<com.github.iotexproject.grpc.types.EvmTransfer>(evmTransfers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.iotexproject.grpc.types.EvmTransfer, com.github.iotexproject.grpc.types.EvmTransfer.Builder, com.github.iotexproject.grpc.types.EvmTransferOrBuilder> evmTransfersBuilder_;

    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public java.util.List<com.github.iotexproject.grpc.types.EvmTransfer> getEvmTransfersList() {
      if (evmTransfersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(evmTransfers_);
      } else {
        return evmTransfersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public int getEvmTransfersCount() {
      if (evmTransfersBuilder_ == null) {
        return evmTransfers_.size();
      } else {
        return evmTransfersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public com.github.iotexproject.grpc.types.EvmTransfer getEvmTransfers(int index) {
      if (evmTransfersBuilder_ == null) {
        return evmTransfers_.get(index);
      } else {
        return evmTransfersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder setEvmTransfers(
        int index, com.github.iotexproject.grpc.types.EvmTransfer value) {
      if (evmTransfersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvmTransfersIsMutable();
        evmTransfers_.set(index, value);
        onChanged();
      } else {
        evmTransfersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder setEvmTransfers(
        int index, com.github.iotexproject.grpc.types.EvmTransfer.Builder builderForValue) {
      if (evmTransfersBuilder_ == null) {
        ensureEvmTransfersIsMutable();
        evmTransfers_.set(index, builderForValue.build());
        onChanged();
      } else {
        evmTransfersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder addEvmTransfers(com.github.iotexproject.grpc.types.EvmTransfer value) {
      if (evmTransfersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvmTransfersIsMutable();
        evmTransfers_.add(value);
        onChanged();
      } else {
        evmTransfersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder addEvmTransfers(
        int index, com.github.iotexproject.grpc.types.EvmTransfer value) {
      if (evmTransfersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEvmTransfersIsMutable();
        evmTransfers_.add(index, value);
        onChanged();
      } else {
        evmTransfersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder addEvmTransfers(
        com.github.iotexproject.grpc.types.EvmTransfer.Builder builderForValue) {
      if (evmTransfersBuilder_ == null) {
        ensureEvmTransfersIsMutable();
        evmTransfers_.add(builderForValue.build());
        onChanged();
      } else {
        evmTransfersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder addEvmTransfers(
        int index, com.github.iotexproject.grpc.types.EvmTransfer.Builder builderForValue) {
      if (evmTransfersBuilder_ == null) {
        ensureEvmTransfersIsMutable();
        evmTransfers_.add(index, builderForValue.build());
        onChanged();
      } else {
        evmTransfersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder addAllEvmTransfers(
        java.lang.Iterable<? extends com.github.iotexproject.grpc.types.EvmTransfer> values) {
      if (evmTransfersBuilder_ == null) {
        ensureEvmTransfersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, evmTransfers_);
        onChanged();
      } else {
        evmTransfersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder clearEvmTransfers() {
      if (evmTransfersBuilder_ == null) {
        evmTransfers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        evmTransfersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public Builder removeEvmTransfers(int index) {
      if (evmTransfersBuilder_ == null) {
        ensureEvmTransfersIsMutable();
        evmTransfers_.remove(index);
        onChanged();
      } else {
        evmTransfersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public com.github.iotexproject.grpc.types.EvmTransfer.Builder getEvmTransfersBuilder(
        int index) {
      return getEvmTransfersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public com.github.iotexproject.grpc.types.EvmTransferOrBuilder getEvmTransfersOrBuilder(
        int index) {
      if (evmTransfersBuilder_ == null) {
        return evmTransfers_.get(index);  } else {
        return evmTransfersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public java.util.List<? extends com.github.iotexproject.grpc.types.EvmTransferOrBuilder> 
         getEvmTransfersOrBuilderList() {
      if (evmTransfersBuilder_ != null) {
        return evmTransfersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(evmTransfers_);
      }
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public com.github.iotexproject.grpc.types.EvmTransfer.Builder addEvmTransfersBuilder() {
      return getEvmTransfersFieldBuilder().addBuilder(
          com.github.iotexproject.grpc.types.EvmTransfer.getDefaultInstance());
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public com.github.iotexproject.grpc.types.EvmTransfer.Builder addEvmTransfersBuilder(
        int index) {
      return getEvmTransfersFieldBuilder().addBuilder(
          index, com.github.iotexproject.grpc.types.EvmTransfer.getDefaultInstance());
    }
    /**
     * <code>repeated .iotextypes.EvmTransfer evmTransfers = 1;</code>
     */
    public java.util.List<com.github.iotexproject.grpc.types.EvmTransfer.Builder> 
         getEvmTransfersBuilderList() {
      return getEvmTransfersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.iotexproject.grpc.types.EvmTransfer, com.github.iotexproject.grpc.types.EvmTransfer.Builder, com.github.iotexproject.grpc.types.EvmTransferOrBuilder> 
        getEvmTransfersFieldBuilder() {
      if (evmTransfersBuilder_ == null) {
        evmTransfersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.iotexproject.grpc.types.EvmTransfer, com.github.iotexproject.grpc.types.EvmTransfer.Builder, com.github.iotexproject.grpc.types.EvmTransferOrBuilder>(
                evmTransfers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        evmTransfers_ = null;
      }
      return evmTransfersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iotextypes.EvmTransferList)
  }

  // @@protoc_insertion_point(class_scope:iotextypes.EvmTransferList)
  private static final com.github.iotexproject.grpc.types.EvmTransferList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.types.EvmTransferList();
  }

  public static com.github.iotexproject.grpc.types.EvmTransferList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EvmTransferList>
      PARSER = new com.google.protobuf.AbstractParser<EvmTransferList>() {
    @java.lang.Override
    public EvmTransferList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EvmTransferList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EvmTransferList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EvmTransferList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.types.EvmTransferList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

