// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/action.proto

package com.github.iotexproject.grpc.types;

public interface ExecutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotextypes.Execution)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string amount = 1;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 1;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>string contract = 2;</code>
   * @return The contract.
   */
  java.lang.String getContract();
  /**
   * <code>string contract = 2;</code>
   * @return The bytes for contract.
   */
  com.google.protobuf.ByteString
      getContractBytes();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
