// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/genesis.proto

package com.github.iotexproject.grpc.types;

/**
 * Protobuf type {@code iotextypes.GenesisPoll}
 */
public final class GenesisPoll extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iotextypes.GenesisPoll)
    GenesisPollOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenesisPoll.newBuilder() to construct.
  private GenesisPoll(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenesisPoll() {
    registerContractAddress_ = "";
    stakingContractAddress_ = "";
    voteThreshold_ = "";
    scoreThreshold_ = "";
    selfStakingThreshold_ = "";
    delegates_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GenesisPoll();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GenesisPoll(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            enableGravityChainVoting_ = input.readBool();
            break;
          }
          case 16: {

            gravityChainStartHeight_ = input.readUInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            registerContractAddress_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            stakingContractAddress_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            voteThreshold_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            scoreThreshold_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            selfStakingThreshold_ = s;
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              delegates_ = new java.util.ArrayList<com.github.iotexproject.grpc.types.GenesisDelegate>();
              mutable_bitField0_ |= 0x00000001;
            }
            delegates_.add(
                input.readMessage(com.github.iotexproject.grpc.types.GenesisDelegate.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        delegates_ = java.util.Collections.unmodifiableList(delegates_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisPoll_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisPoll_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.types.GenesisPoll.class, com.github.iotexproject.grpc.types.GenesisPoll.Builder.class);
  }

  public static final int ENABLEGRAVITYCHAINVOTING_FIELD_NUMBER = 1;
  private boolean enableGravityChainVoting_;
  /**
   * <code>bool enableGravityChainVoting = 1;</code>
   * @return The enableGravityChainVoting.
   */
  @java.lang.Override
  public boolean getEnableGravityChainVoting() {
    return enableGravityChainVoting_;
  }

  public static final int GRAVITYCHAINSTARTHEIGHT_FIELD_NUMBER = 2;
  private long gravityChainStartHeight_;
  /**
   * <code>uint64 gravityChainStartHeight = 2;</code>
   * @return The gravityChainStartHeight.
   */
  @java.lang.Override
  public long getGravityChainStartHeight() {
    return gravityChainStartHeight_;
  }

  public static final int REGISTERCONTRACTADDRESS_FIELD_NUMBER = 3;
  private volatile java.lang.Object registerContractAddress_;
  /**
   * <code>string registerContractAddress = 3;</code>
   * @return The registerContractAddress.
   */
  @java.lang.Override
  public java.lang.String getRegisterContractAddress() {
    java.lang.Object ref = registerContractAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      registerContractAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string registerContractAddress = 3;</code>
   * @return The bytes for registerContractAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegisterContractAddressBytes() {
    java.lang.Object ref = registerContractAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      registerContractAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAKINGCONTRACTADDRESS_FIELD_NUMBER = 4;
  private volatile java.lang.Object stakingContractAddress_;
  /**
   * <code>string stakingContractAddress = 4;</code>
   * @return The stakingContractAddress.
   */
  @java.lang.Override
  public java.lang.String getStakingContractAddress() {
    java.lang.Object ref = stakingContractAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stakingContractAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string stakingContractAddress = 4;</code>
   * @return The bytes for stakingContractAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStakingContractAddressBytes() {
    java.lang.Object ref = stakingContractAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stakingContractAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOTETHRESHOLD_FIELD_NUMBER = 5;
  private volatile java.lang.Object voteThreshold_;
  /**
   * <code>string voteThreshold = 5;</code>
   * @return The voteThreshold.
   */
  @java.lang.Override
  public java.lang.String getVoteThreshold() {
    java.lang.Object ref = voteThreshold_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      voteThreshold_ = s;
      return s;
    }
  }
  /**
   * <code>string voteThreshold = 5;</code>
   * @return The bytes for voteThreshold.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVoteThresholdBytes() {
    java.lang.Object ref = voteThreshold_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      voteThreshold_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORETHRESHOLD_FIELD_NUMBER = 6;
  private volatile java.lang.Object scoreThreshold_;
  /**
   * <code>string scoreThreshold = 6;</code>
   * @return The scoreThreshold.
   */
  @java.lang.Override
  public java.lang.String getScoreThreshold() {
    java.lang.Object ref = scoreThreshold_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scoreThreshold_ = s;
      return s;
    }
  }
  /**
   * <code>string scoreThreshold = 6;</code>
   * @return The bytes for scoreThreshold.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScoreThresholdBytes() {
    java.lang.Object ref = scoreThreshold_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scoreThreshold_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SELFSTAKINGTHRESHOLD_FIELD_NUMBER = 7;
  private volatile java.lang.Object selfStakingThreshold_;
  /**
   * <code>string selfStakingThreshold = 7;</code>
   * @return The selfStakingThreshold.
   */
  @java.lang.Override
  public java.lang.String getSelfStakingThreshold() {
    java.lang.Object ref = selfStakingThreshold_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      selfStakingThreshold_ = s;
      return s;
    }
  }
  /**
   * <code>string selfStakingThreshold = 7;</code>
   * @return The bytes for selfStakingThreshold.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSelfStakingThresholdBytes() {
    java.lang.Object ref = selfStakingThreshold_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      selfStakingThreshold_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELEGATES_FIELD_NUMBER = 8;
  private java.util.List<com.github.iotexproject.grpc.types.GenesisDelegate> delegates_;
  /**
   * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.iotexproject.grpc.types.GenesisDelegate> getDelegatesList() {
    return delegates_;
  }
  /**
   * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.iotexproject.grpc.types.GenesisDelegateOrBuilder> 
      getDelegatesOrBuilderList() {
    return delegates_;
  }
  /**
   * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
   */
  @java.lang.Override
  public int getDelegatesCount() {
    return delegates_.size();
  }
  /**
   * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.GenesisDelegate getDelegates(int index) {
    return delegates_.get(index);
  }
  /**
   * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.GenesisDelegateOrBuilder getDelegatesOrBuilder(
      int index) {
    return delegates_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (enableGravityChainVoting_ != false) {
      output.writeBool(1, enableGravityChainVoting_);
    }
    if (gravityChainStartHeight_ != 0L) {
      output.writeUInt64(2, gravityChainStartHeight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registerContractAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, registerContractAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stakingContractAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, stakingContractAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voteThreshold_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, voteThreshold_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scoreThreshold_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, scoreThreshold_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(selfStakingThreshold_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, selfStakingThreshold_);
    }
    for (int i = 0; i < delegates_.size(); i++) {
      output.writeMessage(8, delegates_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (enableGravityChainVoting_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, enableGravityChainVoting_);
    }
    if (gravityChainStartHeight_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, gravityChainStartHeight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registerContractAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, registerContractAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stakingContractAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, stakingContractAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voteThreshold_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, voteThreshold_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scoreThreshold_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, scoreThreshold_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(selfStakingThreshold_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, selfStakingThreshold_);
    }
    for (int i = 0; i < delegates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, delegates_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.types.GenesisPoll)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.types.GenesisPoll other = (com.github.iotexproject.grpc.types.GenesisPoll) obj;

    if (getEnableGravityChainVoting()
        != other.getEnableGravityChainVoting()) return false;
    if (getGravityChainStartHeight()
        != other.getGravityChainStartHeight()) return false;
    if (!getRegisterContractAddress()
        .equals(other.getRegisterContractAddress())) return false;
    if (!getStakingContractAddress()
        .equals(other.getStakingContractAddress())) return false;
    if (!getVoteThreshold()
        .equals(other.getVoteThreshold())) return false;
    if (!getScoreThreshold()
        .equals(other.getScoreThreshold())) return false;
    if (!getSelfStakingThreshold()
        .equals(other.getSelfStakingThreshold())) return false;
    if (!getDelegatesList()
        .equals(other.getDelegatesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENABLEGRAVITYCHAINVOTING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnableGravityChainVoting());
    hash = (37 * hash) + GRAVITYCHAINSTARTHEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGravityChainStartHeight());
    hash = (37 * hash) + REGISTERCONTRACTADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getRegisterContractAddress().hashCode();
    hash = (37 * hash) + STAKINGCONTRACTADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getStakingContractAddress().hashCode();
    hash = (37 * hash) + VOTETHRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + getVoteThreshold().hashCode();
    hash = (37 * hash) + SCORETHRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + getScoreThreshold().hashCode();
    hash = (37 * hash) + SELFSTAKINGTHRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + getSelfStakingThreshold().hashCode();
    if (getDelegatesCount() > 0) {
      hash = (37 * hash) + DELEGATES_FIELD_NUMBER;
      hash = (53 * hash) + getDelegatesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.GenesisPoll parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.types.GenesisPoll prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotextypes.GenesisPoll}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotextypes.GenesisPoll)
      com.github.iotexproject.grpc.types.GenesisPollOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisPoll_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisPoll_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.types.GenesisPoll.class, com.github.iotexproject.grpc.types.GenesisPoll.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.types.GenesisPoll.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDelegatesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      enableGravityChainVoting_ = false;

      gravityChainStartHeight_ = 0L;

      registerContractAddress_ = "";

      stakingContractAddress_ = "";

      voteThreshold_ = "";

      scoreThreshold_ = "";

      selfStakingThreshold_ = "";

      if (delegatesBuilder_ == null) {
        delegates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        delegatesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisPoll_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.GenesisPoll getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.types.GenesisPoll.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.GenesisPoll build() {
      com.github.iotexproject.grpc.types.GenesisPoll result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.GenesisPoll buildPartial() {
      com.github.iotexproject.grpc.types.GenesisPoll result = new com.github.iotexproject.grpc.types.GenesisPoll(this);
      int from_bitField0_ = bitField0_;
      result.enableGravityChainVoting_ = enableGravityChainVoting_;
      result.gravityChainStartHeight_ = gravityChainStartHeight_;
      result.registerContractAddress_ = registerContractAddress_;
      result.stakingContractAddress_ = stakingContractAddress_;
      result.voteThreshold_ = voteThreshold_;
      result.scoreThreshold_ = scoreThreshold_;
      result.selfStakingThreshold_ = selfStakingThreshold_;
      if (delegatesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          delegates_ = java.util.Collections.unmodifiableList(delegates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.delegates_ = delegates_;
      } else {
        result.delegates_ = delegatesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.types.GenesisPoll) {
        return mergeFrom((com.github.iotexproject.grpc.types.GenesisPoll)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.types.GenesisPoll other) {
      if (other == com.github.iotexproject.grpc.types.GenesisPoll.getDefaultInstance()) return this;
      if (other.getEnableGravityChainVoting() != false) {
        setEnableGravityChainVoting(other.getEnableGravityChainVoting());
      }
      if (other.getGravityChainStartHeight() != 0L) {
        setGravityChainStartHeight(other.getGravityChainStartHeight());
      }
      if (!other.getRegisterContractAddress().isEmpty()) {
        registerContractAddress_ = other.registerContractAddress_;
        onChanged();
      }
      if (!other.getStakingContractAddress().isEmpty()) {
        stakingContractAddress_ = other.stakingContractAddress_;
        onChanged();
      }
      if (!other.getVoteThreshold().isEmpty()) {
        voteThreshold_ = other.voteThreshold_;
        onChanged();
      }
      if (!other.getScoreThreshold().isEmpty()) {
        scoreThreshold_ = other.scoreThreshold_;
        onChanged();
      }
      if (!other.getSelfStakingThreshold().isEmpty()) {
        selfStakingThreshold_ = other.selfStakingThreshold_;
        onChanged();
      }
      if (delegatesBuilder_ == null) {
        if (!other.delegates_.isEmpty()) {
          if (delegates_.isEmpty()) {
            delegates_ = other.delegates_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDelegatesIsMutable();
            delegates_.addAll(other.delegates_);
          }
          onChanged();
        }
      } else {
        if (!other.delegates_.isEmpty()) {
          if (delegatesBuilder_.isEmpty()) {
            delegatesBuilder_.dispose();
            delegatesBuilder_ = null;
            delegates_ = other.delegates_;
            bitField0_ = (bitField0_ & ~0x00000001);
            delegatesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDelegatesFieldBuilder() : null;
          } else {
            delegatesBuilder_.addAllMessages(other.delegates_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.iotexproject.grpc.types.GenesisPoll parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.iotexproject.grpc.types.GenesisPoll) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean enableGravityChainVoting_ ;
    /**
     * <code>bool enableGravityChainVoting = 1;</code>
     * @return The enableGravityChainVoting.
     */
    @java.lang.Override
    public boolean getEnableGravityChainVoting() {
      return enableGravityChainVoting_;
    }
    /**
     * <code>bool enableGravityChainVoting = 1;</code>
     * @param value The enableGravityChainVoting to set.
     * @return This builder for chaining.
     */
    public Builder setEnableGravityChainVoting(boolean value) {
      
      enableGravityChainVoting_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool enableGravityChainVoting = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnableGravityChainVoting() {
      
      enableGravityChainVoting_ = false;
      onChanged();
      return this;
    }

    private long gravityChainStartHeight_ ;
    /**
     * <code>uint64 gravityChainStartHeight = 2;</code>
     * @return The gravityChainStartHeight.
     */
    @java.lang.Override
    public long getGravityChainStartHeight() {
      return gravityChainStartHeight_;
    }
    /**
     * <code>uint64 gravityChainStartHeight = 2;</code>
     * @param value The gravityChainStartHeight to set.
     * @return This builder for chaining.
     */
    public Builder setGravityChainStartHeight(long value) {
      
      gravityChainStartHeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 gravityChainStartHeight = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGravityChainStartHeight() {
      
      gravityChainStartHeight_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object registerContractAddress_ = "";
    /**
     * <code>string registerContractAddress = 3;</code>
     * @return The registerContractAddress.
     */
    public java.lang.String getRegisterContractAddress() {
      java.lang.Object ref = registerContractAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        registerContractAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string registerContractAddress = 3;</code>
     * @return The bytes for registerContractAddress.
     */
    public com.google.protobuf.ByteString
        getRegisterContractAddressBytes() {
      java.lang.Object ref = registerContractAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registerContractAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string registerContractAddress = 3;</code>
     * @param value The registerContractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setRegisterContractAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      registerContractAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string registerContractAddress = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegisterContractAddress() {
      
      registerContractAddress_ = getDefaultInstance().getRegisterContractAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string registerContractAddress = 3;</code>
     * @param value The bytes for registerContractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setRegisterContractAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      registerContractAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stakingContractAddress_ = "";
    /**
     * <code>string stakingContractAddress = 4;</code>
     * @return The stakingContractAddress.
     */
    public java.lang.String getStakingContractAddress() {
      java.lang.Object ref = stakingContractAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stakingContractAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stakingContractAddress = 4;</code>
     * @return The bytes for stakingContractAddress.
     */
    public com.google.protobuf.ByteString
        getStakingContractAddressBytes() {
      java.lang.Object ref = stakingContractAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stakingContractAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stakingContractAddress = 4;</code>
     * @param value The stakingContractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setStakingContractAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stakingContractAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stakingContractAddress = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStakingContractAddress() {
      
      stakingContractAddress_ = getDefaultInstance().getStakingContractAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string stakingContractAddress = 4;</code>
     * @param value The bytes for stakingContractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setStakingContractAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stakingContractAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object voteThreshold_ = "";
    /**
     * <code>string voteThreshold = 5;</code>
     * @return The voteThreshold.
     */
    public java.lang.String getVoteThreshold() {
      java.lang.Object ref = voteThreshold_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voteThreshold_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string voteThreshold = 5;</code>
     * @return The bytes for voteThreshold.
     */
    public com.google.protobuf.ByteString
        getVoteThresholdBytes() {
      java.lang.Object ref = voteThreshold_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voteThreshold_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string voteThreshold = 5;</code>
     * @param value The voteThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setVoteThreshold(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      voteThreshold_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string voteThreshold = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVoteThreshold() {
      
      voteThreshold_ = getDefaultInstance().getVoteThreshold();
      onChanged();
      return this;
    }
    /**
     * <code>string voteThreshold = 5;</code>
     * @param value The bytes for voteThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setVoteThresholdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      voteThreshold_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object scoreThreshold_ = "";
    /**
     * <code>string scoreThreshold = 6;</code>
     * @return The scoreThreshold.
     */
    public java.lang.String getScoreThreshold() {
      java.lang.Object ref = scoreThreshold_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scoreThreshold_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scoreThreshold = 6;</code>
     * @return The bytes for scoreThreshold.
     */
    public com.google.protobuf.ByteString
        getScoreThresholdBytes() {
      java.lang.Object ref = scoreThreshold_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scoreThreshold_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scoreThreshold = 6;</code>
     * @param value The scoreThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setScoreThreshold(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scoreThreshold_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string scoreThreshold = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearScoreThreshold() {
      
      scoreThreshold_ = getDefaultInstance().getScoreThreshold();
      onChanged();
      return this;
    }
    /**
     * <code>string scoreThreshold = 6;</code>
     * @param value The bytes for scoreThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setScoreThresholdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scoreThreshold_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object selfStakingThreshold_ = "";
    /**
     * <code>string selfStakingThreshold = 7;</code>
     * @return The selfStakingThreshold.
     */
    public java.lang.String getSelfStakingThreshold() {
      java.lang.Object ref = selfStakingThreshold_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selfStakingThreshold_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string selfStakingThreshold = 7;</code>
     * @return The bytes for selfStakingThreshold.
     */
    public com.google.protobuf.ByteString
        getSelfStakingThresholdBytes() {
      java.lang.Object ref = selfStakingThreshold_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selfStakingThreshold_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string selfStakingThreshold = 7;</code>
     * @param value The selfStakingThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setSelfStakingThreshold(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      selfStakingThreshold_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string selfStakingThreshold = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelfStakingThreshold() {
      
      selfStakingThreshold_ = getDefaultInstance().getSelfStakingThreshold();
      onChanged();
      return this;
    }
    /**
     * <code>string selfStakingThreshold = 7;</code>
     * @param value The bytes for selfStakingThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setSelfStakingThresholdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      selfStakingThreshold_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.github.iotexproject.grpc.types.GenesisDelegate> delegates_ =
      java.util.Collections.emptyList();
    private void ensureDelegatesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        delegates_ = new java.util.ArrayList<com.github.iotexproject.grpc.types.GenesisDelegate>(delegates_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.iotexproject.grpc.types.GenesisDelegate, com.github.iotexproject.grpc.types.GenesisDelegate.Builder, com.github.iotexproject.grpc.types.GenesisDelegateOrBuilder> delegatesBuilder_;

    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public java.util.List<com.github.iotexproject.grpc.types.GenesisDelegate> getDelegatesList() {
      if (delegatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(delegates_);
      } else {
        return delegatesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public int getDelegatesCount() {
      if (delegatesBuilder_ == null) {
        return delegates_.size();
      } else {
        return delegatesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public com.github.iotexproject.grpc.types.GenesisDelegate getDelegates(int index) {
      if (delegatesBuilder_ == null) {
        return delegates_.get(index);
      } else {
        return delegatesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder setDelegates(
        int index, com.github.iotexproject.grpc.types.GenesisDelegate value) {
      if (delegatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDelegatesIsMutable();
        delegates_.set(index, value);
        onChanged();
      } else {
        delegatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder setDelegates(
        int index, com.github.iotexproject.grpc.types.GenesisDelegate.Builder builderForValue) {
      if (delegatesBuilder_ == null) {
        ensureDelegatesIsMutable();
        delegates_.set(index, builderForValue.build());
        onChanged();
      } else {
        delegatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder addDelegates(com.github.iotexproject.grpc.types.GenesisDelegate value) {
      if (delegatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDelegatesIsMutable();
        delegates_.add(value);
        onChanged();
      } else {
        delegatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder addDelegates(
        int index, com.github.iotexproject.grpc.types.GenesisDelegate value) {
      if (delegatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDelegatesIsMutable();
        delegates_.add(index, value);
        onChanged();
      } else {
        delegatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder addDelegates(
        com.github.iotexproject.grpc.types.GenesisDelegate.Builder builderForValue) {
      if (delegatesBuilder_ == null) {
        ensureDelegatesIsMutable();
        delegates_.add(builderForValue.build());
        onChanged();
      } else {
        delegatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder addDelegates(
        int index, com.github.iotexproject.grpc.types.GenesisDelegate.Builder builderForValue) {
      if (delegatesBuilder_ == null) {
        ensureDelegatesIsMutable();
        delegates_.add(index, builderForValue.build());
        onChanged();
      } else {
        delegatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder addAllDelegates(
        java.lang.Iterable<? extends com.github.iotexproject.grpc.types.GenesisDelegate> values) {
      if (delegatesBuilder_ == null) {
        ensureDelegatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, delegates_);
        onChanged();
      } else {
        delegatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder clearDelegates() {
      if (delegatesBuilder_ == null) {
        delegates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        delegatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public Builder removeDelegates(int index) {
      if (delegatesBuilder_ == null) {
        ensureDelegatesIsMutable();
        delegates_.remove(index);
        onChanged();
      } else {
        delegatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public com.github.iotexproject.grpc.types.GenesisDelegate.Builder getDelegatesBuilder(
        int index) {
      return getDelegatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public com.github.iotexproject.grpc.types.GenesisDelegateOrBuilder getDelegatesOrBuilder(
        int index) {
      if (delegatesBuilder_ == null) {
        return delegates_.get(index);  } else {
        return delegatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public java.util.List<? extends com.github.iotexproject.grpc.types.GenesisDelegateOrBuilder> 
         getDelegatesOrBuilderList() {
      if (delegatesBuilder_ != null) {
        return delegatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(delegates_);
      }
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public com.github.iotexproject.grpc.types.GenesisDelegate.Builder addDelegatesBuilder() {
      return getDelegatesFieldBuilder().addBuilder(
          com.github.iotexproject.grpc.types.GenesisDelegate.getDefaultInstance());
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public com.github.iotexproject.grpc.types.GenesisDelegate.Builder addDelegatesBuilder(
        int index) {
      return getDelegatesFieldBuilder().addBuilder(
          index, com.github.iotexproject.grpc.types.GenesisDelegate.getDefaultInstance());
    }
    /**
     * <code>repeated .iotextypes.GenesisDelegate delegates = 8;</code>
     */
    public java.util.List<com.github.iotexproject.grpc.types.GenesisDelegate.Builder> 
         getDelegatesBuilderList() {
      return getDelegatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.iotexproject.grpc.types.GenesisDelegate, com.github.iotexproject.grpc.types.GenesisDelegate.Builder, com.github.iotexproject.grpc.types.GenesisDelegateOrBuilder> 
        getDelegatesFieldBuilder() {
      if (delegatesBuilder_ == null) {
        delegatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.iotexproject.grpc.types.GenesisDelegate, com.github.iotexproject.grpc.types.GenesisDelegate.Builder, com.github.iotexproject.grpc.types.GenesisDelegateOrBuilder>(
                delegates_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        delegates_ = null;
      }
      return delegatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iotextypes.GenesisPoll)
  }

  // @@protoc_insertion_point(class_scope:iotextypes.GenesisPoll)
  private static final com.github.iotexproject.grpc.types.GenesisPoll DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.types.GenesisPoll();
  }

  public static com.github.iotexproject.grpc.types.GenesisPoll getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenesisPoll>
      PARSER = new com.google.protobuf.AbstractParser<GenesisPoll>() {
    @java.lang.Override
    public GenesisPoll parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GenesisPoll(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GenesisPoll> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenesisPoll> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.types.GenesisPoll getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

