// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/action.proto

package com.github.iotexproject.grpc.types;

public interface SettleDepositOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotextypes.SettleDeposit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string amount = 1;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 1;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>string recipient = 2;</code>
   * @return The recipient.
   */
  java.lang.String getRecipient();
  /**
   * <code>string recipient = 2;</code>
   * @return The bytes for recipient.
   */
  com.google.protobuf.ByteString
      getRecipientBytes();

  /**
   * <code>uint64 index = 3;</code>
   * @return The index.
   */
  long getIndex();
}
