// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/action.proto

package com.github.iotexproject.grpc.types;

public interface StakeAddDepositOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotextypes.StakeAddDeposit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 bucketIndex = 1;</code>
   * @return The bucketIndex.
   */
  long getBucketIndex();

  /**
   * <code>string amount = 2;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 2;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>bytes payload = 3;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
