// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/action.proto

package com.github.iotexproject.grpc.types;

public interface StakeCreateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotextypes.StakeCreate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string candidateName = 1;</code>
   * @return The candidateName.
   */
  java.lang.String getCandidateName();
  /**
   * <code>string candidateName = 1;</code>
   * @return The bytes for candidateName.
   */
  com.google.protobuf.ByteString
      getCandidateNameBytes();

  /**
   * <code>string stakedAmount = 2;</code>
   * @return The stakedAmount.
   */
  java.lang.String getStakedAmount();
  /**
   * <code>string stakedAmount = 2;</code>
   * @return The bytes for stakedAmount.
   */
  com.google.protobuf.ByteString
      getStakedAmountBytes();

  /**
   * <code>uint32 stakedDuration = 3;</code>
   * @return The stakedDuration.
   */
  int getStakedDuration();

  /**
   * <code>bool autoStake = 4;</code>
   * @return The autoStake.
   */
  boolean getAutoStake();

  /**
   * <code>bytes payload = 5;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
