// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/transaction_log.proto

package com.github.iotexproject.grpc.types;

/**
 * Protobuf type {@code iotextypes.TransactionLog}
 */
public final class TransactionLog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iotextypes.TransactionLog)
    TransactionLogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionLog.newBuilder() to construct.
  private TransactionLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionLog() {
    actionHash_ = com.google.protobuf.ByteString.EMPTY;
    transactions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransactionLog();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionLog(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            actionHash_ = input.readBytes();
            break;
          }
          case 16: {

            numTransactions_ = input.readUInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              transactions_ = new java.util.ArrayList<com.github.iotexproject.grpc.types.TransactionLog.Transaction>();
              mutable_bitField0_ |= 0x00000001;
            }
            transactions_.add(
                input.readMessage(com.github.iotexproject.grpc.types.TransactionLog.Transaction.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        transactions_ = java.util.Collections.unmodifiableList(transactions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.types.TransactionLog.class, com.github.iotexproject.grpc.types.TransactionLog.Builder.class);
  }

  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iotextypes.TransactionLog.Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes topic = 1;</code>
     * @return The topic.
     */
    com.google.protobuf.ByteString getTopic();

    /**
     * <code>string amount = 2;</code>
     * @return The amount.
     */
    java.lang.String getAmount();
    /**
     * <code>string amount = 2;</code>
     * @return The bytes for amount.
     */
    com.google.protobuf.ByteString
        getAmountBytes();

    /**
     * <code>string sender = 3;</code>
     * @return The sender.
     */
    java.lang.String getSender();
    /**
     * <code>string sender = 3;</code>
     * @return The bytes for sender.
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>string recipient = 4;</code>
     * @return The recipient.
     */
    java.lang.String getRecipient();
    /**
     * <code>string recipient = 4;</code>
     * @return The bytes for recipient.
     */
    com.google.protobuf.ByteString
        getRecipientBytes();

    /**
     * <code>.iotextypes.TransactionLogType type = 5;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.iotextypes.TransactionLogType type = 5;</code>
     * @return The type.
     */
    com.github.iotexproject.grpc.types.TransactionLogType getType();
  }
  /**
   * Protobuf type {@code iotextypes.TransactionLog.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iotextypes.TransactionLog.Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      topic_ = com.google.protobuf.ByteString.EMPTY;
      amount_ = "";
      sender_ = "";
      recipient_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Transaction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              topic_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              amount_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              recipient_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_Transaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.types.TransactionLog.Transaction.class, com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder.class);
    }

    public static final int TOPIC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString topic_;
    /**
     * <code>bytes topic = 1;</code>
     * @return The topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTopic() {
      return topic_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private volatile java.lang.Object amount_;
    /**
     * <code>string amount = 2;</code>
     * @return The amount.
     */
    @java.lang.Override
    public java.lang.String getAmount() {
      java.lang.Object ref = amount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        amount_ = s;
        return s;
      }
    }
    /**
     * <code>string amount = 2;</code>
     * @return The bytes for amount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAmountBytes() {
      java.lang.Object ref = amount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        amount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 3;
    private volatile java.lang.Object sender_;
    /**
     * <code>string sender = 3;</code>
     * @return The sender.
     */
    @java.lang.Override
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <code>string sender = 3;</code>
     * @return The bytes for sender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECIPIENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object recipient_;
    /**
     * <code>string recipient = 4;</code>
     * @return The recipient.
     */
    @java.lang.Override
    public java.lang.String getRecipient() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipient_ = s;
        return s;
      }
    }
    /**
     * <code>string recipient = 4;</code>
     * @return The bytes for recipient.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>.iotextypes.TransactionLogType type = 5;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.iotextypes.TransactionLogType type = 5;</code>
     * @return The type.
     */
    @java.lang.Override public com.github.iotexproject.grpc.types.TransactionLogType getType() {
      @SuppressWarnings("deprecation")
      com.github.iotexproject.grpc.types.TransactionLogType result = com.github.iotexproject.grpc.types.TransactionLogType.valueOf(type_);
      return result == null ? com.github.iotexproject.grpc.types.TransactionLogType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!topic_.isEmpty()) {
        output.writeBytes(1, topic_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(amount_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, amount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recipient_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, recipient_);
      }
      if (type_ != com.github.iotexproject.grpc.types.TransactionLogType.IN_CONTRACT_TRANSFER.getNumber()) {
        output.writeEnum(5, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!topic_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, topic_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(amount_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, amount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recipient_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, recipient_);
      }
      if (type_ != com.github.iotexproject.grpc.types.TransactionLogType.IN_CONTRACT_TRANSFER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.iotexproject.grpc.types.TransactionLog.Transaction)) {
        return super.equals(obj);
      }
      com.github.iotexproject.grpc.types.TransactionLog.Transaction other = (com.github.iotexproject.grpc.types.TransactionLog.Transaction) obj;

      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (!getAmount()
          .equals(other.getAmount())) return false;
      if (!getSender()
          .equals(other.getSender())) return false;
      if (!getRecipient()
          .equals(other.getRecipient())) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
      hash = (53 * hash) + getRecipient().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.iotexproject.grpc.types.TransactionLog.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iotextypes.TransactionLog.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iotextypes.TransactionLog.Transaction)
        com.github.iotexproject.grpc.types.TransactionLog.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_Transaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.iotexproject.grpc.types.TransactionLog.Transaction.class, com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder.class);
      }

      // Construct using com.github.iotexproject.grpc.types.TransactionLog.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        topic_ = com.google.protobuf.ByteString.EMPTY;

        amount_ = "";

        sender_ = "";

        recipient_ = "";

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_Transaction_descriptor;
      }

      @java.lang.Override
      public com.github.iotexproject.grpc.types.TransactionLog.Transaction getDefaultInstanceForType() {
        return com.github.iotexproject.grpc.types.TransactionLog.Transaction.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.iotexproject.grpc.types.TransactionLog.Transaction build() {
        com.github.iotexproject.grpc.types.TransactionLog.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.iotexproject.grpc.types.TransactionLog.Transaction buildPartial() {
        com.github.iotexproject.grpc.types.TransactionLog.Transaction result = new com.github.iotexproject.grpc.types.TransactionLog.Transaction(this);
        result.topic_ = topic_;
        result.amount_ = amount_;
        result.sender_ = sender_;
        result.recipient_ = recipient_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.iotexproject.grpc.types.TransactionLog.Transaction) {
          return mergeFrom((com.github.iotexproject.grpc.types.TransactionLog.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.iotexproject.grpc.types.TransactionLog.Transaction other) {
        if (other == com.github.iotexproject.grpc.types.TransactionLog.Transaction.getDefaultInstance()) return this;
        if (other.getTopic() != com.google.protobuf.ByteString.EMPTY) {
          setTopic(other.getTopic());
        }
        if (!other.getAmount().isEmpty()) {
          amount_ = other.amount_;
          onChanged();
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getRecipient().isEmpty()) {
          recipient_ = other.recipient_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.iotexproject.grpc.types.TransactionLog.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.iotexproject.grpc.types.TransactionLog.Transaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString topic_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes topic = 1;</code>
       * @return The topic.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTopic() {
        return topic_;
      }
      /**
       * <code>bytes topic = 1;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes topic = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }

      private java.lang.Object amount_ = "";
      /**
       * <code>string amount = 2;</code>
       * @return The amount.
       */
      public java.lang.String getAmount() {
        java.lang.Object ref = amount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          amount_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string amount = 2;</code>
       * @return The bytes for amount.
       */
      public com.google.protobuf.ByteString
          getAmountBytes() {
        java.lang.Object ref = amount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          amount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string amount = 2;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string amount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = getDefaultInstance().getAmount();
        onChanged();
        return this;
      }
      /**
       * <code>string amount = 2;</code>
       * @param value The bytes for amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        amount_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>string sender = 3;</code>
       * @return The sender.
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender = 3;</code>
       * @return The bytes for sender.
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender = 3;</code>
       * @param value The sender to set.
       * @return This builder for chaining.
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 3;</code>
       * @param value The bytes for sender to set.
       * @return This builder for chaining.
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recipient_ = "";
      /**
       * <code>string recipient = 4;</code>
       * @return The recipient.
       */
      public java.lang.String getRecipient() {
        java.lang.Object ref = recipient_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recipient_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string recipient = 4;</code>
       * @return The bytes for recipient.
       */
      public com.google.protobuf.ByteString
          getRecipientBytes() {
        java.lang.Object ref = recipient_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recipient_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string recipient = 4;</code>
       * @param value The recipient to set.
       * @return This builder for chaining.
       */
      public Builder setRecipient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recipient_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string recipient = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecipient() {
        
        recipient_ = getDefaultInstance().getRecipient();
        onChanged();
        return this;
      }
      /**
       * <code>string recipient = 4;</code>
       * @param value The bytes for recipient to set.
       * @return This builder for chaining.
       */
      public Builder setRecipientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recipient_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.iotextypes.TransactionLogType type = 5;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.iotextypes.TransactionLogType type = 5;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.iotextypes.TransactionLogType type = 5;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.github.iotexproject.grpc.types.TransactionLogType getType() {
        @SuppressWarnings("deprecation")
        com.github.iotexproject.grpc.types.TransactionLogType result = com.github.iotexproject.grpc.types.TransactionLogType.valueOf(type_);
        return result == null ? com.github.iotexproject.grpc.types.TransactionLogType.UNRECOGNIZED : result;
      }
      /**
       * <code>.iotextypes.TransactionLogType type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.github.iotexproject.grpc.types.TransactionLogType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.iotextypes.TransactionLogType type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iotextypes.TransactionLog.Transaction)
    }

    // @@protoc_insertion_point(class_scope:iotextypes.TransactionLog.Transaction)
    private static final com.github.iotexproject.grpc.types.TransactionLog.Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.iotexproject.grpc.types.TransactionLog.Transaction();
    }

    public static com.github.iotexproject.grpc.types.TransactionLog.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      @java.lang.Override
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.TransactionLog.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ACTIONHASH_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString actionHash_;
  /**
   * <code>bytes actionHash = 1;</code>
   * @return The actionHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getActionHash() {
    return actionHash_;
  }

  public static final int NUMTRANSACTIONS_FIELD_NUMBER = 2;
  private long numTransactions_;
  /**
   * <code>uint64 numTransactions = 2;</code>
   * @return The numTransactions.
   */
  @java.lang.Override
  public long getNumTransactions() {
    return numTransactions_;
  }

  public static final int TRANSACTIONS_FIELD_NUMBER = 3;
  private java.util.List<com.github.iotexproject.grpc.types.TransactionLog.Transaction> transactions_;
  /**
   * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.iotexproject.grpc.types.TransactionLog.Transaction> getTransactionsList() {
    return transactions_;
  }
  /**
   * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.iotexproject.grpc.types.TransactionLog.TransactionOrBuilder> 
      getTransactionsOrBuilderList() {
    return transactions_;
  }
  /**
   * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
   */
  @java.lang.Override
  public int getTransactionsCount() {
    return transactions_.size();
  }
  /**
   * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.TransactionLog.Transaction getTransactions(int index) {
    return transactions_.get(index);
  }
  /**
   * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.TransactionLog.TransactionOrBuilder getTransactionsOrBuilder(
      int index) {
    return transactions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!actionHash_.isEmpty()) {
      output.writeBytes(1, actionHash_);
    }
    if (numTransactions_ != 0L) {
      output.writeUInt64(2, numTransactions_);
    }
    for (int i = 0; i < transactions_.size(); i++) {
      output.writeMessage(3, transactions_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!actionHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, actionHash_);
    }
    if (numTransactions_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, numTransactions_);
    }
    for (int i = 0; i < transactions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, transactions_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.types.TransactionLog)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.types.TransactionLog other = (com.github.iotexproject.grpc.types.TransactionLog) obj;

    if (!getActionHash()
        .equals(other.getActionHash())) return false;
    if (getNumTransactions()
        != other.getNumTransactions()) return false;
    if (!getTransactionsList()
        .equals(other.getTransactionsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTIONHASH_FIELD_NUMBER;
    hash = (53 * hash) + getActionHash().hashCode();
    hash = (37 * hash) + NUMTRANSACTIONS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumTransactions());
    if (getTransactionsCount() > 0) {
      hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.TransactionLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.types.TransactionLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotextypes.TransactionLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotextypes.TransactionLog)
      com.github.iotexproject.grpc.types.TransactionLogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.types.TransactionLog.class, com.github.iotexproject.grpc.types.TransactionLog.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.types.TransactionLog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransactionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      actionHash_ = com.google.protobuf.ByteString.EMPTY;

      numTransactions_ = 0L;

      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        transactionsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionLog_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.TransactionLog getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.types.TransactionLog.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.TransactionLog build() {
      com.github.iotexproject.grpc.types.TransactionLog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.TransactionLog buildPartial() {
      com.github.iotexproject.grpc.types.TransactionLog result = new com.github.iotexproject.grpc.types.TransactionLog(this);
      int from_bitField0_ = bitField0_;
      result.actionHash_ = actionHash_;
      result.numTransactions_ = numTransactions_;
      if (transactionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.transactions_ = transactions_;
      } else {
        result.transactions_ = transactionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.types.TransactionLog) {
        return mergeFrom((com.github.iotexproject.grpc.types.TransactionLog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.types.TransactionLog other) {
      if (other == com.github.iotexproject.grpc.types.TransactionLog.getDefaultInstance()) return this;
      if (other.getActionHash() != com.google.protobuf.ByteString.EMPTY) {
        setActionHash(other.getActionHash());
      }
      if (other.getNumTransactions() != 0L) {
        setNumTransactions(other.getNumTransactions());
      }
      if (transactionsBuilder_ == null) {
        if (!other.transactions_.isEmpty()) {
          if (transactions_.isEmpty()) {
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTransactionsIsMutable();
            transactions_.addAll(other.transactions_);
          }
          onChanged();
        }
      } else {
        if (!other.transactions_.isEmpty()) {
          if (transactionsBuilder_.isEmpty()) {
            transactionsBuilder_.dispose();
            transactionsBuilder_ = null;
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            transactionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTransactionsFieldBuilder() : null;
          } else {
            transactionsBuilder_.addAllMessages(other.transactions_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.iotexproject.grpc.types.TransactionLog parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.iotexproject.grpc.types.TransactionLog) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString actionHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes actionHash = 1;</code>
     * @return The actionHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getActionHash() {
      return actionHash_;
    }
    /**
     * <code>bytes actionHash = 1;</code>
     * @param value The actionHash to set.
     * @return This builder for chaining.
     */
    public Builder setActionHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      actionHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes actionHash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearActionHash() {
      
      actionHash_ = getDefaultInstance().getActionHash();
      onChanged();
      return this;
    }

    private long numTransactions_ ;
    /**
     * <code>uint64 numTransactions = 2;</code>
     * @return The numTransactions.
     */
    @java.lang.Override
    public long getNumTransactions() {
      return numTransactions_;
    }
    /**
     * <code>uint64 numTransactions = 2;</code>
     * @param value The numTransactions to set.
     * @return This builder for chaining.
     */
    public Builder setNumTransactions(long value) {
      
      numTransactions_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 numTransactions = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumTransactions() {
      
      numTransactions_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.github.iotexproject.grpc.types.TransactionLog.Transaction> transactions_ =
      java.util.Collections.emptyList();
    private void ensureTransactionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        transactions_ = new java.util.ArrayList<com.github.iotexproject.grpc.types.TransactionLog.Transaction>(transactions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.iotexproject.grpc.types.TransactionLog.Transaction, com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder, com.github.iotexproject.grpc.types.TransactionLog.TransactionOrBuilder> transactionsBuilder_;

    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public java.util.List<com.github.iotexproject.grpc.types.TransactionLog.Transaction> getTransactionsList() {
      if (transactionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transactions_);
      } else {
        return transactionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public int getTransactionsCount() {
      if (transactionsBuilder_ == null) {
        return transactions_.size();
      } else {
        return transactionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public com.github.iotexproject.grpc.types.TransactionLog.Transaction getTransactions(int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);
      } else {
        return transactionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder setTransactions(
        int index, com.github.iotexproject.grpc.types.TransactionLog.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.set(index, value);
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder setTransactions(
        int index, com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.set(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder addTransactions(com.github.iotexproject.grpc.types.TransactionLog.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder addTransactions(
        int index, com.github.iotexproject.grpc.types.TransactionLog.Transaction value) {
      if (transactionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransactionsIsMutable();
        transactions_.add(index, value);
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder addTransactions(
        com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder addTransactions(
        int index, com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder builderForValue) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.add(index, builderForValue.build());
        onChanged();
      } else {
        transactionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder addAllTransactions(
        java.lang.Iterable<? extends com.github.iotexproject.grpc.types.TransactionLog.Transaction> values) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactions_);
        onChanged();
      } else {
        transactionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder clearTransactions() {
      if (transactionsBuilder_ == null) {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        transactionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public Builder removeTransactions(int index) {
      if (transactionsBuilder_ == null) {
        ensureTransactionsIsMutable();
        transactions_.remove(index);
        onChanged();
      } else {
        transactionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder getTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public com.github.iotexproject.grpc.types.TransactionLog.TransactionOrBuilder getTransactionsOrBuilder(
        int index) {
      if (transactionsBuilder_ == null) {
        return transactions_.get(index);  } else {
        return transactionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public java.util.List<? extends com.github.iotexproject.grpc.types.TransactionLog.TransactionOrBuilder> 
         getTransactionsOrBuilderList() {
      if (transactionsBuilder_ != null) {
        return transactionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transactions_);
      }
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder addTransactionsBuilder() {
      return getTransactionsFieldBuilder().addBuilder(
          com.github.iotexproject.grpc.types.TransactionLog.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder addTransactionsBuilder(
        int index) {
      return getTransactionsFieldBuilder().addBuilder(
          index, com.github.iotexproject.grpc.types.TransactionLog.Transaction.getDefaultInstance());
    }
    /**
     * <code>repeated .iotextypes.TransactionLog.Transaction transactions = 3;</code>
     */
    public java.util.List<com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder> 
         getTransactionsBuilderList() {
      return getTransactionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.iotexproject.grpc.types.TransactionLog.Transaction, com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder, com.github.iotexproject.grpc.types.TransactionLog.TransactionOrBuilder> 
        getTransactionsFieldBuilder() {
      if (transactionsBuilder_ == null) {
        transactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.iotexproject.grpc.types.TransactionLog.Transaction, com.github.iotexproject.grpc.types.TransactionLog.Transaction.Builder, com.github.iotexproject.grpc.types.TransactionLog.TransactionOrBuilder>(
                transactions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        transactions_ = null;
      }
      return transactionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iotextypes.TransactionLog)
  }

  // @@protoc_insertion_point(class_scope:iotextypes.TransactionLog)
  private static final com.github.iotexproject.grpc.types.TransactionLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.types.TransactionLog();
  }

  public static com.github.iotexproject.grpc.types.TransactionLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionLog>
      PARSER = new com.google.protobuf.AbstractParser<TransactionLog>() {
    @java.lang.Override
    public TransactionLog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionLog(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionLog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionLog> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.types.TransactionLog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

