// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/types/transaction_log.proto

package com.github.iotexproject.grpc.types;

/**
 * Protobuf type {@code iotextypes.TransactionStructLog}
 */
public final class TransactionStructLog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:iotextypes.TransactionStructLog)
    TransactionStructLogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransactionStructLog.newBuilder() to construct.
  private TransactionStructLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionStructLog() {
    memory_ = "";
    stack_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    returnData_ = "";
    opName_ = "";
    error_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransactionStructLog();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransactionStructLog(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            pc_ = input.readUInt64();
            break;
          }
          case 16: {

            op_ = input.readUInt64();
            break;
          }
          case 24: {

            gas_ = input.readUInt64();
            break;
          }
          case 32: {

            gasCost_ = input.readUInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            memory_ = s;
            break;
          }
          case 48: {

            memSize_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              stack_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            stack_.add(s);
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            returnData_ = s;
            break;
          }
          case 72: {

            depth_ = input.readInt32();
            break;
          }
          case 80: {

            refund_ = input.readUInt64();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            opName_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            error_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        stack_ = stack_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionStructLog_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionStructLog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.types.TransactionStructLog.class, com.github.iotexproject.grpc.types.TransactionStructLog.Builder.class);
  }

  public static final int PC_FIELD_NUMBER = 1;
  private long pc_;
  /**
   * <code>uint64 pc = 1;</code>
   * @return The pc.
   */
  @java.lang.Override
  public long getPc() {
    return pc_;
  }

  public static final int OP_FIELD_NUMBER = 2;
  private long op_;
  /**
   * <code>uint64 op = 2;</code>
   * @return The op.
   */
  @java.lang.Override
  public long getOp() {
    return op_;
  }

  public static final int GAS_FIELD_NUMBER = 3;
  private long gas_;
  /**
   * <code>uint64 gas = 3;</code>
   * @return The gas.
   */
  @java.lang.Override
  public long getGas() {
    return gas_;
  }

  public static final int GASCOST_FIELD_NUMBER = 4;
  private long gasCost_;
  /**
   * <code>uint64 gasCost = 4;</code>
   * @return The gasCost.
   */
  @java.lang.Override
  public long getGasCost() {
    return gasCost_;
  }

  public static final int MEMORY_FIELD_NUMBER = 5;
  private volatile java.lang.Object memory_;
  /**
   * <code>string memory = 5;</code>
   * @return The memory.
   */
  @java.lang.Override
  public java.lang.String getMemory() {
    java.lang.Object ref = memory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      memory_ = s;
      return s;
    }
  }
  /**
   * <code>string memory = 5;</code>
   * @return The bytes for memory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMemoryBytes() {
    java.lang.Object ref = memory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      memory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMSIZE_FIELD_NUMBER = 6;
  private int memSize_;
  /**
   * <code>int32 memSize = 6;</code>
   * @return The memSize.
   */
  @java.lang.Override
  public int getMemSize() {
    return memSize_;
  }

  public static final int STACK_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList stack_;
  /**
   * <code>repeated string stack = 7;</code>
   * @return A list containing the stack.
   */
  public com.google.protobuf.ProtocolStringList
      getStackList() {
    return stack_;
  }
  /**
   * <code>repeated string stack = 7;</code>
   * @return The count of stack.
   */
  public int getStackCount() {
    return stack_.size();
  }
  /**
   * <code>repeated string stack = 7;</code>
   * @param index The index of the element to return.
   * @return The stack at the given index.
   */
  public java.lang.String getStack(int index) {
    return stack_.get(index);
  }
  /**
   * <code>repeated string stack = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stack at the given index.
   */
  public com.google.protobuf.ByteString
      getStackBytes(int index) {
    return stack_.getByteString(index);
  }

  public static final int RETURNDATA_FIELD_NUMBER = 8;
  private volatile java.lang.Object returnData_;
  /**
   * <code>string returnData = 8;</code>
   * @return The returnData.
   */
  @java.lang.Override
  public java.lang.String getReturnData() {
    java.lang.Object ref = returnData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnData_ = s;
      return s;
    }
  }
  /**
   * <code>string returnData = 8;</code>
   * @return The bytes for returnData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReturnDataBytes() {
    java.lang.Object ref = returnData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPTH_FIELD_NUMBER = 9;
  private int depth_;
  /**
   * <code>int32 depth = 9;</code>
   * @return The depth.
   */
  @java.lang.Override
  public int getDepth() {
    return depth_;
  }

  public static final int REFUND_FIELD_NUMBER = 10;
  private long refund_;
  /**
   * <code>uint64 refund = 10;</code>
   * @return The refund.
   */
  @java.lang.Override
  public long getRefund() {
    return refund_;
  }

  public static final int OPNAME_FIELD_NUMBER = 11;
  private volatile java.lang.Object opName_;
  /**
   * <code>string opName = 11;</code>
   * @return The opName.
   */
  @java.lang.Override
  public java.lang.String getOpName() {
    java.lang.Object ref = opName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      opName_ = s;
      return s;
    }
  }
  /**
   * <code>string opName = 11;</code>
   * @return The bytes for opName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOpNameBytes() {
    java.lang.Object ref = opName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      opName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 12;
  private volatile java.lang.Object error_;
  /**
   * <code>string error = 12;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 12;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pc_ != 0L) {
      output.writeUInt64(1, pc_);
    }
    if (op_ != 0L) {
      output.writeUInt64(2, op_);
    }
    if (gas_ != 0L) {
      output.writeUInt64(3, gas_);
    }
    if (gasCost_ != 0L) {
      output.writeUInt64(4, gasCost_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memory_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, memory_);
    }
    if (memSize_ != 0) {
      output.writeInt32(6, memSize_);
    }
    for (int i = 0; i < stack_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, stack_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(returnData_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, returnData_);
    }
    if (depth_ != 0) {
      output.writeInt32(9, depth_);
    }
    if (refund_ != 0L) {
      output.writeUInt64(10, refund_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(opName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, opName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, error_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pc_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, pc_);
    }
    if (op_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, op_);
    }
    if (gas_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, gas_);
    }
    if (gasCost_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, gasCost_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memory_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, memory_);
    }
    if (memSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, memSize_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < stack_.size(); i++) {
        dataSize += computeStringSizeNoTag(stack_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStackList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(returnData_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, returnData_);
    }
    if (depth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, depth_);
    }
    if (refund_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(10, refund_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(opName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, opName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, error_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.types.TransactionStructLog)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.types.TransactionStructLog other = (com.github.iotexproject.grpc.types.TransactionStructLog) obj;

    if (getPc()
        != other.getPc()) return false;
    if (getOp()
        != other.getOp()) return false;
    if (getGas()
        != other.getGas()) return false;
    if (getGasCost()
        != other.getGasCost()) return false;
    if (!getMemory()
        .equals(other.getMemory())) return false;
    if (getMemSize()
        != other.getMemSize()) return false;
    if (!getStackList()
        .equals(other.getStackList())) return false;
    if (!getReturnData()
        .equals(other.getReturnData())) return false;
    if (getDepth()
        != other.getDepth()) return false;
    if (getRefund()
        != other.getRefund()) return false;
    if (!getOpName()
        .equals(other.getOpName())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPc());
    hash = (37 * hash) + OP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOp());
    hash = (37 * hash) + GAS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGas());
    hash = (37 * hash) + GASCOST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGasCost());
    hash = (37 * hash) + MEMORY_FIELD_NUMBER;
    hash = (53 * hash) + getMemory().hashCode();
    hash = (37 * hash) + MEMSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getMemSize();
    if (getStackCount() > 0) {
      hash = (37 * hash) + STACK_FIELD_NUMBER;
      hash = (53 * hash) + getStackList().hashCode();
    }
    hash = (37 * hash) + RETURNDATA_FIELD_NUMBER;
    hash = (53 * hash) + getReturnData().hashCode();
    hash = (37 * hash) + DEPTH_FIELD_NUMBER;
    hash = (53 * hash) + getDepth();
    hash = (37 * hash) + REFUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRefund());
    hash = (37 * hash) + OPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getOpName().hashCode();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.TransactionStructLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.types.TransactionStructLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotextypes.TransactionStructLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotextypes.TransactionStructLog)
      com.github.iotexproject.grpc.types.TransactionStructLogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionStructLog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionStructLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.types.TransactionStructLog.class, com.github.iotexproject.grpc.types.TransactionStructLog.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.types.TransactionStructLog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pc_ = 0L;

      op_ = 0L;

      gas_ = 0L;

      gasCost_ = 0L;

      memory_ = "";

      memSize_ = 0;

      stack_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      returnData_ = "";

      depth_ = 0;

      refund_ = 0L;

      opName_ = "";

      error_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.types.TransactionLogOuterClass.internal_static_iotextypes_TransactionStructLog_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.TransactionStructLog getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.types.TransactionStructLog.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.TransactionStructLog build() {
      com.github.iotexproject.grpc.types.TransactionStructLog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.TransactionStructLog buildPartial() {
      com.github.iotexproject.grpc.types.TransactionStructLog result = new com.github.iotexproject.grpc.types.TransactionStructLog(this);
      int from_bitField0_ = bitField0_;
      result.pc_ = pc_;
      result.op_ = op_;
      result.gas_ = gas_;
      result.gasCost_ = gasCost_;
      result.memory_ = memory_;
      result.memSize_ = memSize_;
      if (((bitField0_ & 0x00000001) != 0)) {
        stack_ = stack_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.stack_ = stack_;
      result.returnData_ = returnData_;
      result.depth_ = depth_;
      result.refund_ = refund_;
      result.opName_ = opName_;
      result.error_ = error_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.types.TransactionStructLog) {
        return mergeFrom((com.github.iotexproject.grpc.types.TransactionStructLog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.types.TransactionStructLog other) {
      if (other == com.github.iotexproject.grpc.types.TransactionStructLog.getDefaultInstance()) return this;
      if (other.getPc() != 0L) {
        setPc(other.getPc());
      }
      if (other.getOp() != 0L) {
        setOp(other.getOp());
      }
      if (other.getGas() != 0L) {
        setGas(other.getGas());
      }
      if (other.getGasCost() != 0L) {
        setGasCost(other.getGasCost());
      }
      if (!other.getMemory().isEmpty()) {
        memory_ = other.memory_;
        onChanged();
      }
      if (other.getMemSize() != 0) {
        setMemSize(other.getMemSize());
      }
      if (!other.stack_.isEmpty()) {
        if (stack_.isEmpty()) {
          stack_ = other.stack_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureStackIsMutable();
          stack_.addAll(other.stack_);
        }
        onChanged();
      }
      if (!other.getReturnData().isEmpty()) {
        returnData_ = other.returnData_;
        onChanged();
      }
      if (other.getDepth() != 0) {
        setDepth(other.getDepth());
      }
      if (other.getRefund() != 0L) {
        setRefund(other.getRefund());
      }
      if (!other.getOpName().isEmpty()) {
        opName_ = other.opName_;
        onChanged();
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.iotexproject.grpc.types.TransactionStructLog parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.iotexproject.grpc.types.TransactionStructLog) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long pc_ ;
    /**
     * <code>uint64 pc = 1;</code>
     * @return The pc.
     */
    @java.lang.Override
    public long getPc() {
      return pc_;
    }
    /**
     * <code>uint64 pc = 1;</code>
     * @param value The pc to set.
     * @return This builder for chaining.
     */
    public Builder setPc(long value) {
      
      pc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 pc = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPc() {
      
      pc_ = 0L;
      onChanged();
      return this;
    }

    private long op_ ;
    /**
     * <code>uint64 op = 2;</code>
     * @return The op.
     */
    @java.lang.Override
    public long getOp() {
      return op_;
    }
    /**
     * <code>uint64 op = 2;</code>
     * @param value The op to set.
     * @return This builder for chaining.
     */
    public Builder setOp(long value) {
      
      op_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 op = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOp() {
      
      op_ = 0L;
      onChanged();
      return this;
    }

    private long gas_ ;
    /**
     * <code>uint64 gas = 3;</code>
     * @return The gas.
     */
    @java.lang.Override
    public long getGas() {
      return gas_;
    }
    /**
     * <code>uint64 gas = 3;</code>
     * @param value The gas to set.
     * @return This builder for chaining.
     */
    public Builder setGas(long value) {
      
      gas_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 gas = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGas() {
      
      gas_ = 0L;
      onChanged();
      return this;
    }

    private long gasCost_ ;
    /**
     * <code>uint64 gasCost = 4;</code>
     * @return The gasCost.
     */
    @java.lang.Override
    public long getGasCost() {
      return gasCost_;
    }
    /**
     * <code>uint64 gasCost = 4;</code>
     * @param value The gasCost to set.
     * @return This builder for chaining.
     */
    public Builder setGasCost(long value) {
      
      gasCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 gasCost = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasCost() {
      
      gasCost_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object memory_ = "";
    /**
     * <code>string memory = 5;</code>
     * @return The memory.
     */
    public java.lang.String getMemory() {
      java.lang.Object ref = memory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string memory = 5;</code>
     * @return The bytes for memory.
     */
    public com.google.protobuf.ByteString
        getMemoryBytes() {
      java.lang.Object ref = memory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string memory = 5;</code>
     * @param value The memory to set.
     * @return This builder for chaining.
     */
    public Builder setMemory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      memory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string memory = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemory() {
      
      memory_ = getDefaultInstance().getMemory();
      onChanged();
      return this;
    }
    /**
     * <code>string memory = 5;</code>
     * @param value The bytes for memory to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      memory_ = value;
      onChanged();
      return this;
    }

    private int memSize_ ;
    /**
     * <code>int32 memSize = 6;</code>
     * @return The memSize.
     */
    @java.lang.Override
    public int getMemSize() {
      return memSize_;
    }
    /**
     * <code>int32 memSize = 6;</code>
     * @param value The memSize to set.
     * @return This builder for chaining.
     */
    public Builder setMemSize(int value) {
      
      memSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 memSize = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemSize() {
      
      memSize_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList stack_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureStackIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        stack_ = new com.google.protobuf.LazyStringArrayList(stack_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @return A list containing the stack.
     */
    public com.google.protobuf.ProtocolStringList
        getStackList() {
      return stack_.getUnmodifiableView();
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @return The count of stack.
     */
    public int getStackCount() {
      return stack_.size();
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @param index The index of the element to return.
     * @return The stack at the given index.
     */
    public java.lang.String getStack(int index) {
      return stack_.get(index);
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stack at the given index.
     */
    public com.google.protobuf.ByteString
        getStackBytes(int index) {
      return stack_.getByteString(index);
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @param index The index to set the value at.
     * @param value The stack to set.
     * @return This builder for chaining.
     */
    public Builder setStack(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStackIsMutable();
      stack_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @param value The stack to add.
     * @return This builder for chaining.
     */
    public Builder addStack(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStackIsMutable();
      stack_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @param values The stack to add.
     * @return This builder for chaining.
     */
    public Builder addAllStack(
        java.lang.Iterable<java.lang.String> values) {
      ensureStackIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stack_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStack() {
      stack_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 7;</code>
     * @param value The bytes of the stack to add.
     * @return This builder for chaining.
     */
    public Builder addStackBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureStackIsMutable();
      stack_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object returnData_ = "";
    /**
     * <code>string returnData = 8;</code>
     * @return The returnData.
     */
    public java.lang.String getReturnData() {
      java.lang.Object ref = returnData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string returnData = 8;</code>
     * @return The bytes for returnData.
     */
    public com.google.protobuf.ByteString
        getReturnDataBytes() {
      java.lang.Object ref = returnData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string returnData = 8;</code>
     * @param value The returnData to set.
     * @return This builder for chaining.
     */
    public Builder setReturnData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string returnData = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearReturnData() {
      
      returnData_ = getDefaultInstance().getReturnData();
      onChanged();
      return this;
    }
    /**
     * <code>string returnData = 8;</code>
     * @param value The bytes for returnData to set.
     * @return This builder for chaining.
     */
    public Builder setReturnDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnData_ = value;
      onChanged();
      return this;
    }

    private int depth_ ;
    /**
     * <code>int32 depth = 9;</code>
     * @return The depth.
     */
    @java.lang.Override
    public int getDepth() {
      return depth_;
    }
    /**
     * <code>int32 depth = 9;</code>
     * @param value The depth to set.
     * @return This builder for chaining.
     */
    public Builder setDepth(int value) {
      
      depth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 depth = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDepth() {
      
      depth_ = 0;
      onChanged();
      return this;
    }

    private long refund_ ;
    /**
     * <code>uint64 refund = 10;</code>
     * @return The refund.
     */
    @java.lang.Override
    public long getRefund() {
      return refund_;
    }
    /**
     * <code>uint64 refund = 10;</code>
     * @param value The refund to set.
     * @return This builder for chaining.
     */
    public Builder setRefund(long value) {
      
      refund_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 refund = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefund() {
      
      refund_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object opName_ = "";
    /**
     * <code>string opName = 11;</code>
     * @return The opName.
     */
    public java.lang.String getOpName() {
      java.lang.Object ref = opName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        opName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string opName = 11;</code>
     * @return The bytes for opName.
     */
    public com.google.protobuf.ByteString
        getOpNameBytes() {
      java.lang.Object ref = opName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        opName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string opName = 11;</code>
     * @param value The opName to set.
     * @return This builder for chaining.
     */
    public Builder setOpName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      opName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string opName = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpName() {
      
      opName_ = getDefaultInstance().getOpName();
      onChanged();
      return this;
    }
    /**
     * <code>string opName = 11;</code>
     * @param value The bytes for opName to set.
     * @return This builder for chaining.
     */
    public Builder setOpNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      opName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 12;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 12;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 12;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      error_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      
      error_ = getDefaultInstance().getError();
      onChanged();
      return this;
    }
    /**
     * <code>string error = 12;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      error_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:iotextypes.TransactionStructLog)
  }

  // @@protoc_insertion_point(class_scope:iotextypes.TransactionStructLog)
  private static final com.github.iotexproject.grpc.types.TransactionStructLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.types.TransactionStructLog();
  }

  public static com.github.iotexproject.grpc.types.TransactionStructLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionStructLog>
      PARSER = new com.google.protobuf.AbstractParser<TransactionStructLog>() {
    @java.lang.Override
    public TransactionStructLog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransactionStructLog(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionStructLog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionStructLog> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.types.TransactionStructLog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

